"""Pay for Secure Data (x402) — trust-gated Strands buyer agent.

App-backend script that:
  1. Installs the Python dependencies (handled out of band by the user)
  2. Loads .env (USER_ID auto-generated by setup-env.sh on first run)
  3. Demonstrates the deterministic trust guardrail with MOCKS (no AWS, no money)
  4. Provisions the AgentCore payments stack inline:
       one Credential Provider (Coinbase CDP) -> one Manager -> one Connector
  5. Creates one EMBEDDED_CRYPTO_WALLET instrument and a spending-limit-capped
       payment session, then prints the delegated-signing + funding steps
  6. Builds the trust-gated agent (two tools + AgentCorePaymentsPlugin)
  7. Runs the agent LIVE against t54 x402-secure and the target x402 service
       (interactive prompt: Enter to spend real USDC, q to skip)
  8. Deploys the agent to AgentCore Runtime via CodeBuild and invokes it
       (interactive prompt: Enter to deploy, q to skip)
  9. Inspects the data plane (session spending limit, balance, lists)
 10. Cleanup (revoke session, delete payments resources, destroy runtime)
       (interactive prompt: Enter to clean up, q to skip)

Usage:
    python pay_for_x402_secure_data.py

Prerequisites:
    bash test/integration/setup-env.sh        # generates USER_ID, seeds .env
    cp env-sample.txt .env                    # then fill in Coinbase secrets + INSTRUMENT_EMAIL
    bash test/integration/setup-roles.sh      # creates the four IAM roles

The agent is designed so that it never holds private keys. AgentCore Identity
stores wallet-provider secrets in AWS Secrets Manager under KMS encryption after
CreatePaymentCredentialProvider runs in §4. The agent runtime calls
GetResourcePaymentToken at signing time and never receives the raw secret. Every
target x402 payment is gated in code by TrustedX402ServiceGateway behind a paid
t54 x402-secure trust check.

Compliance note: this sample settles real cryptocurrency (USDC) payments.
Processing payments can carry regulatory obligations — for example
financial-services regulations, AML/KYC requirements for cryptocurrency
transactions, sanctions screening, and PCI-DSS where card data is involved —
that vary by jurisdiction and use case. You are responsible for determining and
meeting the requirements that apply to you. Review the AWS Shared Responsibility
Model (https://aws.amazon.com/compliance/shared-responsibility-model/) and AWS
Compliance Programs (https://aws.amazon.com/compliance/programs/), and consult
your own legal and compliance advisors before processing payments in production.
"""

from __future__ import annotations

import contextlib
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import uuid

import boto3
import botocore.exceptions
from boto3.session import Session
from dotenv import load_dotenv

HERE = pathlib.Path(__file__).resolve().parent
# The agent modules (agent.py, x402_*.py, payments.py) live in agent/container.
sys.path.insert(0, str(HERE / "agent" / "container"))

from utils import assume_role, idempotent_create, wait_for_status, write_env_updates

# ── §2. Configure environment ────────────────────────────────────────────────
load_dotenv(override=True)

AWS_REGION = os.environ.get("AWS_REGION", "us-west-2")
BEDROCK_MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")

CONTROL_PLANE_ROLE_ARN = os.environ.get("CONTROL_PLANE_ROLE_ARN", "")
MANAGEMENT_ROLE_ARN = os.environ.get("MANAGEMENT_ROLE_ARN", "")
PROCESS_PAYMENT_ROLE_ARN = os.environ.get("PROCESS_PAYMENT_ROLE_ARN", "")
RESOURCE_RETRIEVAL_ROLE_ARN = os.environ.get("RESOURCE_RETRIEVAL_ROLE_ARN", "")

COINBASE_API_KEY_ID = os.environ.get("COINBASE_API_KEY_ID", "")
COINBASE_API_KEY_SECRET = os.environ.get("COINBASE_API_KEY_SECRET", "")
COINBASE_WALLET_SECRET = os.environ.get("COINBASE_WALLET_SECRET", "")

MANAGER_ARN = os.environ.get("MANAGER_ARN", "")
PAYMENT_CONNECTOR_ID = os.environ.get("PAYMENT_CONNECTOR_ID", "")
CREDENTIAL_PROVIDER_ARN = os.environ.get("CREDENTIAL_PROVIDER_ARN", "")
PAYMENT_INSTRUMENT_ID = os.environ.get("PAYMENT_INSTRUMENT_ID", "")
PAYMENT_SESSION_ID = os.environ.get("PAYMENT_SESSION_ID", "")
WALLET_ADDRESS = os.environ.get("WALLET_ADDRESS", "")

USER_ID = os.environ.get("USER_ID") or f"x402-secure-data-{uuid.uuid4()}"
INSTRUMENT_EMAIL = os.environ.get("INSTRUMENT_EMAIL", "")
PAYMENT_INSTRUMENT_NETWORK = os.environ.get("PAYMENT_INSTRUMENT_NETWORK", "ETHEREUM")
PAYMENT_SESSION_MAX_SPEND_USD = os.environ.get("PAYMENT_SESSION_MAX_SPEND_USD", "1.0")
PAYMENT_SESSION_EXPIRY_MINUTES = int(os.environ.get("PAYMENT_SESSION_EXPIRY_MINUTES", "60"))

MANAGER_ID = MANAGER_ARN.rsplit("/", 1)[-1] if MANAGER_ARN else ""


def _client_token() -> str:
    """AgentCore payments requires clientToken >= 33 chars (idempotency token)."""
    return f"{uuid.uuid4()}-{uuid.uuid4().hex[:8]}"


def _safe_name(prefix: str) -> str:
    name = f"{prefix}{uuid.uuid4().hex[:8]}"
    assert re.match(r"^[a-zA-Z][a-zA-Z0-9]{0,47}$", name), name
    return name


def _env_flag(name: str) -> bool:
    """True if the named .env gate is set to 1/true/yes (default off)."""
    return os.environ.get(name, "0").strip().lower() in ("1", "true", "yes")


def _confirm_section(title: str, body_lines: list[str], action_label: str, require_yes: bool = False) -> bool:
    """Show a framed banner + body, then prompt for confirmation.

    Default: Enter runs the step, q + Enter skips it. When require_yes is set
    (used for destructive steps like cleanup), the default flips to skip — the
    user must type 'yes' to proceed, and anything else is treated as skip.
    """
    print("\n" + "=" * 72)
    print(f"  {title}")
    print("=" * 72)
    for line in body_lines:
        print(line)
    if require_yes:
        print(f"\n  ▶▶ Type 'yes' + Enter to {action_label}. Anything else skips.")
        return input("     [type 'yes' to confirm | Enter to skip] ").strip().lower() in ("yes", "y")
    print(f"\n  ▶▶ Press Enter to {action_label}, or press q + Enter to skip.")
    return input("     [Enter to continue | q to skip] ").strip().lower() not in ("q", "quit", "skip", "n", "no")


def _is_set(value: str) -> bool:
    return bool(value) and not value.startswith("<")


def _run_env_check() -> None:
    # Non-secret values are safe to echo. Secret values are kept in a separate
    # map and are ONLY ever checked for presence — their values never flow into
    # a printed string, so nothing sensitive is logged in clear text.
    visible = {
        "AWS_REGION": AWS_REGION,
        "CONTROL_PLANE_ROLE_ARN": CONTROL_PLANE_ROLE_ARN,
        "MANAGEMENT_ROLE_ARN": MANAGEMENT_ROLE_ARN,
        "PROCESS_PAYMENT_ROLE_ARN": PROCESS_PAYMENT_ROLE_ARN,
        "RESOURCE_RETRIEVAL_ROLE_ARN": RESOURCE_RETRIEVAL_ROLE_ARN,
        "INSTRUMENT_EMAIL": INSTRUMENT_EMAIL,
    }
    # These are the Coinbase env-var NAMES to display (not their values). Named
    # without "secret"/"key" so static analysis does not misclassify the printed
    # variable name as a sensitive value.
    coinbase_env_names = ("COINBASE_API_KEY_ID", "COINBASE_API_KEY_SECRET", "COINBASE_WALLET_SECRET")

    print("=== Environment check ===")
    missing = []
    for key, value in visible.items():
        ok = _is_set(value)
        print(f"  {'✅' if ok else '❌ MISSING'}  {key}: {value if ok else '(missing)'}")
        if not ok:
            missing.append(key)

    # Check the secrets for presence only. The secret values (and any variable
    # derived from them) are never referenced in a printed string — only the
    # literal key name is appended to `missing`, so nothing sensitive is logged.
    if not _is_set(COINBASE_API_KEY_ID):
        missing.append("COINBASE_API_KEY_ID")
    if not _is_set(COINBASE_API_KEY_SECRET):
        missing.append("COINBASE_API_KEY_SECRET")
    if not _is_set(COINBASE_WALLET_SECRET):
        missing.append("COINBASE_WALLET_SECRET")

    # Render status from the (literal) missing-name list, so the printed line
    # never references a secret value or a secret-derived variable.
    for name in coinbase_env_names:
        present = name not in missing
        print(f"  {'✅' if present else '❌ MISSING'}  {name}: {'[redacted]' if present else '(missing)'}")

    if INSTRUMENT_EMAIL.lower().endswith("@example.com"):
        sys.exit("INSTRUMENT_EMAIL must be a REAL, deliverable address — not an @example.com placeholder.")
    if missing:
        sys.exit(f"\n❌ {len(missing)} required value(s) missing in .env. Fix them, save, then re-run.")
    print("\n✅ Environment check passed.\n")


# ── §3. Guardrail demo (mocks, no AWS, no money) ─────────────────────────────
def guardrail_demo() -> None:
    from x402_services import (
        DEFAULT_SERVICE_ID,
        HEURIST_YAHOO_FINANCE_OPERATIONS,
        TrustedX402ServiceGateway,
        resolve_heurist_base_url,
        use_request_trust_state,
    )

    print("=== §3. Trust guardrail demo (mocks — no AWS calls, no payments) ===")
    target_url = resolve_heurist_base_url()

    class DemoTrustClient:
        def __init__(self, result):
            self.result = result

        def score_endpoint(self, url, headers=None):
            return self.result

    class DemoServiceClient:
        def call_operation(self, operation, payload, headers=None):
            return {"operation": operation, "data": "<mocked market data>"}

    def make_gateway(trust_result):
        services = {
            DEFAULT_SERVICE_ID: {
                "base_url": target_url,
                "operations": HEURIST_YAHOO_FINANCE_OPERATIONS,
                "client": DemoServiceClient(),
            }
        }
        return TrustedX402ServiceGateway(
            services=services,
            trust_client=DemoTrustClient(trust_result),
            trust_threshold=50,
            fail_closed=True,
        )

    for label, trust in (
        ("Approved (score 91)", {"overall_score": 91, "risk_level": "low", "is_scam": False}),
        ("Blocked — low score (23)", {"overall_score": 23, "risk_level": "high", "is_scam": False}),
        ("Blocked — scam flagged", {"overall_score": 88, "risk_level": "critical", "is_scam": True}),
    ):
        with use_request_trust_state():
            gw = make_gateway(trust)
            gw.check_x402_endpoint_trust(DEFAULT_SERVICE_ID)
            result = gw.call_trusted_x402_service(DEFAULT_SERVICE_ID, "quote_snapshot", {"symbols": "AAPL"})
            status = result.get("status", "called") if isinstance(result, dict) else result
            print(f"  {label} -> {'🚫 ' + result['reason'] if status == 'blocked' else '✅ target called'}")
    print("\n  The target service is only reached on the approved path.\n")


# ── §4. Set up AgentCore payments (credential provider, manager, connector) ──
def build_control_client() -> boto3.client:
    for name, val in (
        ("CONTROL_PLANE_ROLE_ARN", CONTROL_PLANE_ROLE_ARN),
        ("RESOURCE_RETRIEVAL_ROLE_ARN", RESOURCE_RETRIEVAL_ROLE_ARN),
    ):
        if not val:
            sys.exit(f"Missing {name}. Run bash test/integration/setup-roles.sh.")
    print("Assuming ControlPlaneRole...")
    cp_session = assume_role(Session(region_name=AWS_REGION), CONTROL_PLANE_ROLE_ARN, "x402-secure-cp")
    return cp_session.client("bedrock-agentcore-control")


def setup_payments(cp_client) -> None:
    global CREDENTIAL_PROVIDER_ARN, MANAGER_ARN, MANAGER_ID, PAYMENT_CONNECTOR_ID

    if CREDENTIAL_PROVIDER_ARN:
        print("↷ CREDENTIAL_PROVIDER_ARN already set, skipping credential provider create")
    else:
        resp = idempotent_create(
            cp_client.create_payment_credential_provider,
            conflict_msg="Credential provider already exists",
            name=_safe_name("CoinbaseCdp"),
            credentialProviderVendor="CoinbaseCDP",
            providerConfigurationInput={
                "coinbaseCdpConfiguration": {
                    "apiKeyId": COINBASE_API_KEY_ID,
                    "apiKeySecret": COINBASE_API_KEY_SECRET,
                    "walletSecret": COINBASE_WALLET_SECRET,
                }
            },
        )
        if resp is None:
            sys.exit("Credential provider already exists — rename or delete it.")
        CREDENTIAL_PROVIDER_ARN = resp["credentialProviderArn"]
        write_env_updates({"CREDENTIAL_PROVIDER_ARN": CREDENTIAL_PROVIDER_ARN})
        print("✅ Credential provider created")

    if MANAGER_ARN:
        print("↷ MANAGER_ARN already set, skipping manager create")
    else:
        resp = cp_client.create_payment_manager(
            name=_safe_name("X402SecureData"),
            description="AgentCore payments Pay for Secure Data (x402)",
            authorizerType="AWS_IAM",
            roleArn=RESOURCE_RETRIEVAL_ROLE_ARN,
            clientToken=_client_token(),
        )
        MANAGER_ID = resp["paymentManagerId"]
        MANAGER_ARN = resp["paymentManagerArn"]
        wait_for_status(cp_client.get_payment_manager, expected_status="READY", paymentManagerId=MANAGER_ID)
        write_env_updates({"MANAGER_ARN": MANAGER_ARN})
        print(f"✅ Manager READY: {MANAGER_ARN}")
    MANAGER_ID = MANAGER_ARN.rsplit("/", 1)[-1]

    if PAYMENT_CONNECTOR_ID:
        print("↷ PAYMENT_CONNECTOR_ID already set, skipping connector create")
    else:
        resp = cp_client.create_payment_connector(
            paymentManagerId=MANAGER_ID,
            name=_safe_name("CoinbaseConnector"),
            description="AgentCore payments CoinbaseCDP connector",
            type="CoinbaseCDP",
            credentialProviderConfigurations=[{"coinbaseCDP": {"credentialProviderArn": CREDENTIAL_PROVIDER_ARN}}],
            clientToken=_client_token(),
        )
        PAYMENT_CONNECTOR_ID = resp["paymentConnectorId"]
        wait_for_status(
            cp_client.get_payment_connector,
            expected_status="READY",
            paymentManagerId=MANAGER_ID,
            paymentConnectorId=PAYMENT_CONNECTOR_ID,
        )
        write_env_updates({"PAYMENT_CONNECTOR_ID": PAYMENT_CONNECTOR_ID})
        print(f"✅ Connector READY: {PAYMENT_CONNECTOR_ID}")


# ── §5. Create instrument + session ──────────────────────────────────────────
def setup_instrument_and_session(mgmt_client) -> None:
    global PAYMENT_INSTRUMENT_ID, PAYMENT_SESSION_ID, WALLET_ADDRESS
    redirect_url = None

    if PAYMENT_INSTRUMENT_ID:
        print("↷ PAYMENT_INSTRUMENT_ID already set, skipping instrument create")
        # Re-fetch the instrument so the onboarding block below can still show
        # the actual (clickable) Wallet Hub link and wallet address on a re-run.
        try:
            crypto = mgmt_client.get_payment_instrument(
                paymentManagerArn=MANAGER_ARN,
                paymentInstrumentId=PAYMENT_INSTRUMENT_ID,
                userId=USER_ID,
            )["paymentInstrument"]["paymentInstrumentDetails"]["embeddedCryptoWallet"]
            WALLET_ADDRESS = crypto.get("walletAddress", WALLET_ADDRESS)
            redirect_url = crypto.get("redirectUrl")
        except botocore.exceptions.ClientError as exc:
            print(f"   (could not re-fetch Wallet Hub link: {exc.response['Error']['Code']})")
    else:
        resp = mgmt_client.create_payment_instrument(
            paymentManagerArn=MANAGER_ARN,
            paymentConnectorId=PAYMENT_CONNECTOR_ID,
            userId=USER_ID,
            paymentInstrumentType="EMBEDDED_CRYPTO_WALLET",
            paymentInstrumentDetails={
                "embeddedCryptoWallet": {
                    "network": PAYMENT_INSTRUMENT_NETWORK,
                    "linkedAccounts": [{"email": {"emailAddress": INSTRUMENT_EMAIL}}],
                }
            },
            clientToken=_client_token(),
        )
        PAYMENT_INSTRUMENT_ID = resp["paymentInstrument"]["paymentInstrumentId"]
        wait_for_status(
            mgmt_client.get_payment_instrument,
            expected_status="ACTIVE",
            paymentManagerArn=MANAGER_ARN,
            paymentInstrumentId=PAYMENT_INSTRUMENT_ID,
            userId=USER_ID,
        )
        crypto = mgmt_client.get_payment_instrument(
            paymentManagerArn=MANAGER_ARN,
            paymentInstrumentId=PAYMENT_INSTRUMENT_ID,
            userId=USER_ID,
        )["paymentInstrument"]["paymentInstrumentDetails"]["embeddedCryptoWallet"]
        WALLET_ADDRESS = crypto.get("walletAddress", "")
        redirect_url = crypto.get("redirectUrl")
        write_env_updates({"PAYMENT_INSTRUMENT_ID": PAYMENT_INSTRUMENT_ID, "WALLET_ADDRESS": WALLET_ADDRESS})
        print(f"✅ Instrument ACTIVE (wallet={WALLET_ADDRESS or 'pending'})")

    print("\n  ONE-TIME ONBOARDING (both delegated-signing layers are required):")
    print("   1. Project policy: CDP Portal → Wallets → Non-custodial Wallet → Security → Delegated signing (2FA).")
    if redirect_url:
        print(
            f"   2. Per-wallet grant: sign in to the Wallet Hub with INSTRUMENT_EMAIL and grant delegation:\n      {redirect_url}"
        )
    else:
        print(
            "   2. Per-wallet grant: open the Wallet Hub redirectUrl, sign in with INSTRUMENT_EMAIL, grant delegation."
        )
    print(f"   3. Fund the wallet with USDC on {PAYMENT_INSTRUMENT_NETWORK} (Base): {WALLET_ADDRESS or '(pending)'}")

    if PAYMENT_SESSION_ID:
        print("↷ PAYMENT_SESSION_ID already set, skipping session create")
    else:
        resp = mgmt_client.create_payment_session(
            paymentManagerArn=MANAGER_ARN,
            userId=USER_ID,
            expiryTimeInMinutes=PAYMENT_SESSION_EXPIRY_MINUTES,
            limits={"maxSpendAmount": {"value": str(PAYMENT_SESSION_MAX_SPEND_USD), "currency": "USD"}},
            clientToken=_client_token(),
        )
        PAYMENT_SESSION_ID = resp["paymentSession"]["paymentSessionId"]
        write_env_updates({"PAYMENT_SESSION_ID": PAYMENT_SESSION_ID})
        print(
            f"✅ Session created (spending limit ${PAYMENT_SESSION_MAX_SPEND_USD} USD, expiry {PAYMENT_SESSION_EXPIRY_MINUTES} min)"
        )


# ── §7. Live trust-gated run ─────────────────────────────────────────────────
def run_agent_live() -> None:
    os.environ.update(
        {
            "MANAGER_ARN": MANAGER_ARN,
            "PAYMENT_CONNECTOR_ID": PAYMENT_CONNECTOR_ID,
            "PAYMENT_SESSION_ID": PAYMENT_SESSION_ID,
            "PAYMENT_INSTRUMENT_ID": PAYMENT_INSTRUMENT_ID,
            "USER_ID": USER_ID,
            "BEDROCK_MODEL_ID": BEDROCK_MODEL_ID,
        }
    )
    import agent as agent_module
    from x402_services import use_request_trust_state

    prompt = "Check trust for heurist_yahoo_finance, then fetch a quote snapshot for AAPL."
    print(f"Prompt: {prompt}\n")
    agent = agent_module.create_agent()
    with use_request_trust_state():
        result = agent(prompt)
    print("\n── Agent response ──")
    print(result)


# ── §8. Deploy + invoke the runtime ──────────────────────────────────────────
def deploy_and_invoke_runtime() -> None:
    # Fixed command list (no shell, no untrusted input); runs the sample's own
    # vendored deploy script from a known relative path.
    # check=False: the return code is inspected explicitly below so the failure
    # message can name the script rather than raising CalledProcessError.
    proc = subprocess.run(["bash", "test/integration/deploy-agent.sh"], cwd=HERE, check=False)  # nosec B603
    if proc.returncode != 0:
        sys.exit(f"deploy-agent.sh exited {proc.returncode}")
    outputs = json.loads((HERE / "agent" / "cdk" / "outputs.json").read_text())[
        "AgentCorePaymentsX402SecureDataAgentStack"
    ]
    runtime_arn = outputs["AgentRuntimeArn"]
    print(f"✅ Runtime deployed: {runtime_arn}")
    print("\n  Enable Transaction Search on the runtime in the console for full")
    print("  observability (see README → 'AgentCore Runtime deploy, invoke, observe').")

    runtime_client = boto3.client("bedrock-agentcore", region_name=AWS_REGION)
    resp = runtime_client.invoke_agent_runtime(
        agentRuntimeArn=runtime_arn,
        qualifier="DEFAULT",
        payload=json.dumps(
            {
                "input": {
                    "prompt": "Check the registered x402 market-data service, then fetch a quote snapshot for AAPL.",
                    "payment_context": {
                        "user_id": USER_ID,
                        "payment_session_id": PAYMENT_SESSION_ID,
                        "payment_instrument_id": PAYMENT_INSTRUMENT_ID,
                    },
                }
            }
        ).encode(),
    )
    body = resp["response"]
    data = b"".join(body.iter_chunks()) if hasattr(body, "iter_chunks") else body.read()
    parsed = json.loads(data)
    _print_runtime_result(parsed)


def _print_runtime_result(parsed: dict) -> None:
    """Render the runtime invoke response and flag whether the agent finished.

    The container returns the agent's final message under output.message. A
    completed turn ends on assistant text (the answer). If the final message
    still ends on a toolUse block, the agent stopped mid-loop (the tool was
    requested but the result/answer never came back) — surface that clearly
    rather than printing a raw dict that looks truncated.
    """
    message = parsed.get("output", {}).get("message", parsed)
    content = message.get("content", []) if isinstance(message, dict) else []

    texts = [b["text"] for b in content if isinstance(b, dict) and b.get("text")]
    tool_uses = [b["toolUse"] for b in content if isinstance(b, dict) and b.get("toolUse")]

    print("\n── Runtime invoke result ──")
    for text in texts:
        print(text)

    if tool_uses and not texts:
        tool_names = ", ".join(t.get("name", "?") for t in tool_uses)
        print(
            "⚠️  The agent's final message ended on a tool request "
            f"({tool_names}) with no answer text.\n"
            "   The runtime returns the agent's last message only, so the tool\n"
            "   result did not make it into a final answer. Check the runtime's\n"
            "   CloudWatch logs / observability dashboard for the tool outcome\n"
            "   (a ProcessPayment error or a blocked-trust result will show there)."
        )
    elif not texts and not tool_uses:
        # Unexpected shape — fall back to the raw payload so nothing is hidden.
        print(json.dumps(parsed, indent=2, default=str))


# ── §9. Inspect the data plane ───────────────────────────────────────────────
def inspect_data_plane(mgmt_client) -> None:
    def _payment_user_id() -> str:
        return mgmt_client.get_payment_instrument(
            paymentManagerArn=MANAGER_ARN, paymentInstrumentId=PAYMENT_INSTRUMENT_ID, userId=USER_ID
        )["paymentInstrument"]["userId"]

    # GetPaymentSession — spending-limit state and remaining spend.
    resp = mgmt_client.get_payment_session(
        paymentManagerArn=MANAGER_ARN, paymentSessionId=PAYMENT_SESSION_ID, userId=USER_ID
    )
    s = resp.get("paymentSession", {})
    limit_amt = s.get("limits", {}).get("maxSpendAmount", {})
    avail = s.get("availableLimits", {}).get("availableSpendAmount", {})
    print("── Payment session ──")
    print(f"  Spending limit: {limit_amt.get('value', '?')} {limit_amt.get('currency', '')}")
    print(f"  Remaining:      {avail.get('value', '?')} {avail.get('currency', '')}")
    print(f"  Expires in:     {s.get('expiryTimeInMinutes', '?')} minutes")

    # GetPaymentInstrumentBalance — on-chain USDC balance.
    try:
        chain = "BASE" if PAYMENT_INSTRUMENT_NETWORK == "ETHEREUM" else "SOLANA"
        bal_resp = mgmt_client.get_payment_instrument_balance(
            paymentManagerArn=MANAGER_ARN,
            paymentConnectorId=PAYMENT_CONNECTOR_ID,
            paymentInstrumentId=PAYMENT_INSTRUMENT_ID,
            userId=_payment_user_id(),
            chain=chain,
            token="USDC",  # nosec B106 — public token symbol, not a credential
        )
        bal = bal_resp.get("tokenBalance", {})
        amount = int(bal.get("amount", "0")) / (10 ** int(bal.get("decimals", 6)))
        print(f"\n── Wallet balance ({chain}) ──")
        print(f"  Wallet:  {WALLET_ADDRESS}")
        print(f"  Balance: {amount:.6f} {bal.get('token', 'USDC')}")
    except botocore.exceptions.ClientError as exc:
        print(f"\n  ⚠️  GetPaymentInstrumentBalance: {exc.response['Error']['Code']}")

    # ListPaymentInstruments — every instrument under this connector.
    try:
        insts = mgmt_client.list_payment_instruments(
            paymentManagerArn=MANAGER_ARN,
            paymentConnectorId=PAYMENT_CONNECTOR_ID,
            userId=_payment_user_id(),
            maxResults=20,
        ).get("paymentInstruments", [])
        print(f"\n── Payment instruments ({len(insts)}) ──")
        for it in insts:
            print(f"  {it.get('paymentInstrumentId')}  ({it.get('status', '?')})")
    except botocore.exceptions.ClientError as exc:
        print(f"\n  ⚠️  ListPaymentInstruments: {exc.response['Error']['Code']}")

    # ListPaymentSessions — every session under this manager.
    try:
        sess = mgmt_client.list_payment_sessions(
            paymentManagerArn=MANAGER_ARN,
            userId=USER_ID,
            maxResults=20,
        ).get("paymentSessions", [])
        print(f"\n── Payment sessions ({len(sess)}) ──")
        for se in sess:
            print(f"  {se.get('paymentSessionId')}  (expires in {se.get('expiryTimeInMinutes', '?')} min)")
    except botocore.exceptions.ClientError as exc:
        print(f"\n  ⚠️  ListPaymentSessions: {exc.response['Error']['Code']}")


# ── §10. Cleanup ─────────────────────────────────────────────────────────────
def _safe_delete(fn, label, **kwargs):
    try:
        fn(**kwargs)
        print(f"  ✅ Deleted: {label}")
    except botocore.exceptions.ClientError as exc:
        code = exc.response["Error"]["Code"]
        msg = exc.response["Error"].get("Message", "")
        if code == "ResourceNotFoundException" or (code == "AccessDeniedException" and "not found" in msg.lower()):
            print(f"  ⚠️  Not found: {label}")
        else:
            raise


def cleanup(cp_client, mgmt_client) -> None:
    # Best-effort: cleanup must proceed even if the instrument is already gone,
    # so fall back to USER_ID rather than aborting the teardown.
    payment_user_id = USER_ID
    with contextlib.suppress(Exception):
        payment_user_id = mgmt_client.get_payment_instrument(
            paymentManagerArn=MANAGER_ARN, paymentInstrumentId=PAYMENT_INSTRUMENT_ID, userId=USER_ID
        )["paymentInstrument"]["userId"]

    if PAYMENT_SESSION_ID:
        _safe_delete(
            mgmt_client.delete_payment_session,
            f"Session {PAYMENT_SESSION_ID}",
            paymentManagerArn=MANAGER_ARN,
            paymentSessionId=PAYMENT_SESSION_ID,
            userId=payment_user_id,
        )
    if PAYMENT_INSTRUMENT_ID and PAYMENT_CONNECTOR_ID:
        _safe_delete(
            mgmt_client.delete_payment_instrument,
            f"Instrument {PAYMENT_INSTRUMENT_ID}",
            paymentManagerArn=MANAGER_ARN,
            paymentConnectorId=PAYMENT_CONNECTOR_ID,
            paymentInstrumentId=PAYMENT_INSTRUMENT_ID,
            userId=payment_user_id,
        )
    if PAYMENT_CONNECTOR_ID:
        _safe_delete(
            cp_client.delete_payment_connector,
            f"Connector {PAYMENT_CONNECTOR_ID}",
            paymentManagerId=MANAGER_ID,
            paymentConnectorId=PAYMENT_CONNECTOR_ID,
            clientToken=_client_token(),
        )
    _safe_delete(
        cp_client.delete_payment_manager,
        f"Manager {MANAGER_ID}",
        paymentManagerId=MANAGER_ID,
        clientToken=_client_token(),
    )
    if CREDENTIAL_PROVIDER_ARN:
        _safe_delete(
            cp_client.delete_payment_credential_provider,
            f"Credential provider {CREDENTIAL_PROVIDER_ARN.rsplit('/', 1)[-1]}",
            name=CREDENTIAL_PROVIDER_ARN.rsplit("/", 1)[-1],
        )

    write_env_updates(
        {
            k: ""
            for k in (
                "MANAGER_ARN",
                "PAYMENT_CONNECTOR_ID",
                "CREDENTIAL_PROVIDER_ARN",
                "PAYMENT_INSTRUMENT_ID",
                "PAYMENT_SESSION_ID",
                "WALLET_ADDRESS",
            )
        }
    )
    # Fixed command list (no shell, no untrusted input).
    subprocess.run(["bash", "test/integration/destroy-agent.sh"], cwd=HERE, check=False)  # nosec B603

    _remove_local_artifacts()
    print("\n✅ Cleanup complete.")


def _remove_local_artifacts() -> None:
    """Remove the local CDK build artifacts (venv, cdk.out, outputs.json, caches).

    Mirrors §10.3 of the workshop notebook. AWS resources are already torn down
    above; this leaves only the tracked source files in the use-case folder.
    """
    targets = [
        HERE / "agent" / "cdk" / ".venv",
        HERE / "agent" / "cdk" / "cdk.out",
        HERE / "agent" / "cdk" / "outputs.json",
        HERE / "agent" / "cdk" / "__pycache__",
        HERE / "agent" / "container" / "__pycache__",
        HERE / "__pycache__",
    ]
    print("\n── Local build artifacts ──")
    for path in targets:
        if not path.exists():
            print(f"  ↷ skip (absent): {path.relative_to(HERE)}")
            continue
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()
        print(f"  🗑️  removed: {path.relative_to(HERE)}")


def main() -> None:
    print("=" * 72)
    print("  Pay for Secure Data (x402) — trust-gated agent")
    print("=" * 72)
    _run_env_check()

    # §3 — always runs; no AWS, no money.
    guardrail_demo()

    # §4 + §5 — provision payments resources.
    cp_client = build_control_client()
    setup_payments(cp_client)
    mgmt_session = assume_role(Session(region_name=AWS_REGION), MANAGEMENT_ROLE_ARN, "x402-secure-mgmt")
    mgmt_client = mgmt_session.client("bedrock-agentcore")
    setup_instrument_and_session(mgmt_client)

    # §6 — one-time onboarding gate. A live run cannot settle a payment until
    # BOTH delegated-signing layers are granted AND the wallet is funded, so
    # pause here (when a live run is requested) and wait for explicit
    # confirmation. This prevents ProcessPayment from failing on an unfunded /
    # undelegated wallet immediately after the session is created.
    onboarding_confirmed = False
    if _env_flag("RUN_LIVE") or _env_flag("RUN_LIVE_RUNTIME"):
        onboarding_confirmed = _confirm_section(
            "§6. One-time onboarding — complete before any live paid run",
            [
                "  A live run settles REAL USDC. Before continuing you MUST have:",
                "    1. Granted delegated signing at BOTH layers (project policy +",
                "       the per-wallet Wallet Hub grant printed above).",
                f"    2. Funded the wallet with USDC on {PAYMENT_INSTRUMENT_NETWORK} (Base):",
                f"         {WALLET_ADDRESS or '(see the address printed above)'}",
                "  Verify the wallet balance is non-zero before you continue.",
            ],
            "confirm delegation is granted and the wallet is funded, and continue",
        )
        if not onboarding_confirmed:
            print("\n↷ Onboarding not confirmed — skipping the live run and deploy.")
            print("   Grant delegation, fund the wallet, then re-run.")

    # §7 — live paid run. Gated on RUN_LIVE in .env (default off) AND on the
    # onboarding confirmation above. Each approved run settles REAL USDC twice
    # (the t54 x402-secure trust check and the target service call).
    if _env_flag("RUN_LIVE") and onboarding_confirmed:
        run_agent_live()
    elif not _env_flag("RUN_LIVE"):
        print("\n↷ §7 skipped — RUN_LIVE is not set in .env. Set RUN_LIVE=1 to run the")
        print("   live trust-gated flow (spends real USDC) after delegation + funding.")

    # §8 — deploy to runtime + live invoke. Gated on RUN_LIVE_RUNTIME in .env
    # AND the onboarding confirmation (the deployed runtime also spends real USDC).
    # A second interactive gate here gives a deliberate pause before the deploy:
    # this step provisions infrastructure (CodeBuild + CDK) and the invoke
    # settles REAL USDC, and it must not run straight into §10 cleanup.
    if _env_flag("RUN_LIVE_RUNTIME") and onboarding_confirmed:
        if _confirm_section(
            "§8. Deploy to AgentCore Runtime + live invoke",
            [
                "  This builds the container, deploys the CDK runtime stack, and",
                "  invokes the runtime with a real prompt. The invoke settles REAL",
                "  USDC (trust check + target service call), and the deploy provisions",
                "  billable infrastructure that remains until §10 cleanup.",
            ],
            "deploy the runtime and invoke it live",
        ):
            deploy_and_invoke_runtime()
        else:
            print("\n↷ §8 skipped — runtime deploy/invoke not confirmed.")
    elif not _env_flag("RUN_LIVE_RUNTIME"):
        print("\n↷ §8 skipped — RUN_LIVE_RUNTIME is not set in .env. Set RUN_LIVE_RUNTIME=1")
        print("   to build + deploy the AgentCore Runtime and invoke it live.")

    # §9 — inspect.
    try:
        inspect_data_plane(mgmt_client)
    except botocore.exceptions.ClientError as exc:
        print(f"⚠️  Data-plane inspection skipped: {exc.response['Error']['Code']}")

    # §10 — cleanup (gated, destructive: defaults to skip, requires 'yes').
    if _confirm_section(
        "§10. Cleanup",
        [
            "  Revokes the session and deletes the instrument, connector, manager,",
            "  credential provider, and the agent runtime stack.",
            "  This is destructive and cannot be undone.",
        ],
        "tear everything down",
        require_yes=True,
    ):
        cleanup(cp_client, mgmt_client)
    else:
        print("↷ Skipped cleanup — resources remain and continue to bill.")


if __name__ == "__main__":
    try:
        main()
    except botocore.exceptions.ClientError as exc:
        code = exc.response.get("Error", {}).get("Code", "Unknown")
        sys.exit(f"AWS API error: {code}. See local AWS logs for details.")
