"""Pay-for-API — Strands buyer agent that pays autonomously for a metered HTTP API.

App-backend script that:
  1. Installs the Python dependencies (handled out of band by the user)
  2. Loads .env (USER_ID auto-generated by setup-env.sh on first run)
  3. Deploys the Fun Facts seller stack (CDK -> API Gateway + Lambda + x402)
       (auto-runs deploy-seller.sh on first run; idempotent thereafter)
  4. Provisions the AgentCore Payments stack:
       Two Credential Providers (Coinbase CDP + Stripe via Privy)
       -> one Manager
       -> two Connectors (CDP + Privy)
       -> four Instruments (EVM + Solana per provider)
  5. Creates two payment sessions (one per provider) with spend caps
  6. Grants signing delegation:
       - Opens the Coinbase Wallet Hub in the user's browser
       - Clones, installs, and runs the Privy delegation Next.js frontend
         on http://localhost:3000 and waits for the user to grant access
       Press Enter in this terminal once each hub confirms delegation.
  7. Runs the agent four times locally (provider x network matrix)
  8. Deploys the agent to AgentCore Runtime via CodeBuild and invokes it
       (interactive prompt: Enter to deploy, q to skip)
  9. Inspects the data plane (sessions, balances, lists)
 10. Cleanup (revoke sessions, destroy stacks, delete payments resources)
       (interactive prompt: Enter to clean up, q to skip)

Usage:
    python pay_for_api.py

Prerequisites:
    bash test/integration/setup-roles.sh      # creates four IAM roles
    cp env-sample.txt .env                    # then fill in wallet provider secrets
    bash test/integration/setup-env.sh        # generates USER_ID

Notebook companion: see the matching pay-for-api.ipynb under
06-workshops/13-AgentCore-payments/02-use-cases/pay-for-api-agent/ for a
step-by-step walkthrough with markdown commentary and screenshots.

The agent is designed so that it never holds private keys.
AgentCore Identity stores wallet provider secrets in AWS Secrets Manager
under KMS encryption after CreatePaymentCredentialProvider runs in §4.
The agent runtime calls GetResourcePaymentToken at signing time and
never receives the raw secret.
"""

from __future__ import annotations

import json
import os
import pathlib
import signal
import subprocess
import sys
import threading
import time
import uuid
import webbrowser

import boto3
import botocore.exceptions
import requests
from boto3.session import Session
from dotenv import load_dotenv

from utils import (
    assume_role,
    wait_for_status,
    write_env_updates,
)

# ── §2. Configure environment ────────────────────────────────────────────────
load_dotenv(override=True)

AWS_REGION = os.environ.get("AWS_REGION", "us-west-2")

# IAM role ARNs (from setup-roles.sh)
CONTROL_PLANE_ROLE_ARN = os.environ.get("CONTROL_PLANE_ROLE_ARN", "")
MANAGEMENT_ROLE_ARN = os.environ.get("MANAGEMENT_ROLE_ARN", "")
PROCESS_PAYMENT_ROLE_ARN = os.environ.get("PROCESS_PAYMENT_ROLE_ARN", "")
RESOURCE_RETRIEVAL_ROLE_ARN = os.environ.get("RESOURCE_RETRIEVAL_ROLE_ARN", "")

# Wallet provider secrets (read once to seed CreatePaymentCredentialProvider)
COINBASE_API_KEY_ID = os.environ.get("COINBASE_API_KEY_ID", "")
COINBASE_API_KEY_SECRET = os.environ.get("COINBASE_API_KEY_SECRET", "")
COINBASE_WALLET_SECRET = os.environ.get("COINBASE_WALLET_SECRET", "")

PRIVY_APP_ID = os.environ.get("PRIVY_APP_ID", "")
PRIVY_APP_SECRET = os.environ.get("PRIVY_APP_SECRET", "")
PRIVY_AUTHORIZATION_ID = os.environ.get("PRIVY_AUTHORIZATION_ID", "")
PRIVY_AUTHORIZATION_PRIVATE_KEY = os.environ.get("PRIVY_AUTHORIZATION_PRIVATE_KEY", "")

# Provisioned-resource IDs (populated by §4 / §5; safe to leave blank on first run)
MANAGER_ARN = os.environ.get("MANAGER_ARN", "")
MANAGER_ID = os.environ.get("MANAGER_ID", "")

CREDENTIAL_PROVIDER_ARN_CDP = os.environ.get("CREDENTIAL_PROVIDER_ARN_CDP", "")
CREDENTIAL_PROVIDER_ARN_PRIVY = os.environ.get("CREDENTIAL_PROVIDER_ARN_PRIVY", "")

CONNECTOR_ID_CDP = os.environ.get("CONNECTOR_ID_CDP", "")
CONNECTOR_ID_PRIVY = os.environ.get("CONNECTOR_ID_PRIVY", "")

PAYMENT_INSTRUMENT_ID_CDP_EVM = os.environ.get("PAYMENT_INSTRUMENT_ID_CDP_EVM", "")
WALLET_ADDRESS_CDP_EVM = os.environ.get("WALLET_ADDRESS_CDP_EVM", "")
PAYMENT_INSTRUMENT_ID_CDP_SOL = os.environ.get("PAYMENT_INSTRUMENT_ID_CDP_SOL", "")
WALLET_ADDRESS_CDP_SOL = os.environ.get("WALLET_ADDRESS_CDP_SOL", "")
PAYMENT_INSTRUMENT_ID_PRIVY_EVM = os.environ.get("PAYMENT_INSTRUMENT_ID_PRIVY_EVM", "")
WALLET_ADDRESS_PRIVY_EVM = os.environ.get("WALLET_ADDRESS_PRIVY_EVM", "")
PAYMENT_INSTRUMENT_ID_PRIVY_SOL = os.environ.get("PAYMENT_INSTRUMENT_ID_PRIVY_SOL", "")
WALLET_ADDRESS_PRIVY_SOL = os.environ.get("WALLET_ADDRESS_PRIVY_SOL", "")

SESSION_ID_CDP = os.environ.get("SESSION_ID_CDP", "")
SESSION_ID_PRIVY = os.environ.get("SESSION_ID_PRIVY", "")

SELLER_API_URL = os.environ.get("SELLER_API_URL", "").rstrip("/")
SELLER_WALLET_ADDRESS = os.environ.get("SELLER_WALLET_ADDRESS", "")
SELLER_SOLANA_WALLET_ADDRESS = os.environ.get("SELLER_SOLANA_WALLET_ADDRESS", "")

USER_ID = os.environ.get("USER_ID") or f"pay-for-api-{uuid.uuid4()}"
INSTRUMENT_EMAIL = os.environ.get("INSTRUMENT_EMAIL", f"{USER_ID}@example.com")
SESSION_MAX_SPEND = os.environ.get("SESSION_MAX_SPEND", "1.00")
SESSION_EXPIRY_MINUTES = int(os.environ.get("SESSION_EXPIRY_MINUTES", "30"))


def _check_secret(label: str, value: str, optional: bool = False) -> bool:
    """Pretty-print a sensitive env-var check (e.g., API keys, wallet secrets).

    Sensitive values are NEVER interpolated into stdout. This function uses
    fixed status placeholders only ("[redacted]" / "(unset)" / "(will be
    set later)"), so secret values cannot leak through print(). Callers
    pass redacted values here; non-secrets go to _check_plain() instead.
    """
    ok = bool(value) and not value.startswith("<")
    if optional and not ok:
        print(f"  ⏳  {label}: (will be set later)")
        return True
    if ok:
        print(f"  ✅  {label}: [redacted]")
    else:
        print(f"  ❌ MISSING  {label}: (unset)")
    return ok


def _check_plain(label: str, value: str, optional: bool = False) -> bool:
    """Pretty-print a non-sensitive env-var check (e.g., region, ARN, ID, email).

    Values printed here are non-secrets by contract: AWS region, IAM role
    ARNs, Manager / Connector / Instrument / Session IDs, wallet addresses,
    and the linked email. Variables whose names match CodeQL's sensitivity
    heuristic (e.g., contain `KEY` or `AUTH`) must use _check_secret()
    even when their values are technically public, to keep the static
    analyzer quiet.
    """
    ok = bool(value) and not value.startswith("<")
    display = value
    if optional and not ok:
        display = display or "(will be set later)"
        print(f"  ⏳  {label}: {display}")
        return True
    icon = "✅" if ok else "❌ MISSING"
    print(f"  {icon}  {label}: {display}")
    return ok


def _run_env_check() -> None:
    """Pretty-print the env-check; SystemExit if required values are missing."""
    required_results: list[bool] = []

    print("=== Environment check ===")
    print("\n  AWS:")
    required_results.append(_check_plain("AWS_REGION", AWS_REGION))

    print("\n  IAM roles (from setup-roles.sh):")
    required_results.append(_check_plain("CONTROL_PLANE_ROLE_ARN", CONTROL_PLANE_ROLE_ARN))
    required_results.append(_check_plain("MANAGEMENT_ROLE_ARN", MANAGEMENT_ROLE_ARN))
    required_results.append(_check_plain("PROCESS_PAYMENT_ROLE_ARN", PROCESS_PAYMENT_ROLE_ARN))
    required_results.append(_check_plain("RESOURCE_RETRIEVAL_ROLE_ARN", RESOURCE_RETRIEVAL_ROLE_ARN))

    print("\n  Coinbase CDP secrets:")
    required_results.append(_check_secret("COINBASE_API_KEY_ID", COINBASE_API_KEY_ID))
    required_results.append(_check_secret("COINBASE_API_KEY_SECRET", COINBASE_API_KEY_SECRET))
    required_results.append(_check_secret("COINBASE_WALLET_SECRET", COINBASE_WALLET_SECRET))

    print("\n  Stripe-via-Privy secrets (optional, leave blank to skip Privy):")
    _check_plain("PRIVY_APP_ID", PRIVY_APP_ID, optional=True)
    _check_secret("PRIVY_APP_SECRET", PRIVY_APP_SECRET, optional=True)
    _check_secret("PRIVY_AUTHORIZATION_ID", PRIVY_AUTHORIZATION_ID, optional=True)
    _check_secret("PRIVY_AUTHORIZATION_PRIVATE_KEY", PRIVY_AUTHORIZATION_PRIVATE_KEY, optional=True)

    print("\n  Wallet linked email (used by §4.5 CreatePaymentInstrument):")
    required_results.append(_check_plain("INSTRUMENT_EMAIL", INSTRUMENT_EMAIL))

    print("\n  Seller payout wallets (used by deploy-seller.sh, re-run that script if these change):")
    required_results.append(_check_plain("SELLER_WALLET_ADDRESS", SELLER_WALLET_ADDRESS))
    _check_plain("SELLER_SOLANA_WALLET_ADDRESS", SELLER_SOLANA_WALLET_ADDRESS, optional=True)

    print("\n  Populated later, ⏳ is expected on first run:")
    print("  (deploy-seller.sh writes SELLER_API_URL; §4/§5 write Manager, Connector, Instrument, Session IDs)")
    _check_plain("SELLER_API_URL", SELLER_API_URL, optional=True)
    _check_plain("MANAGER_ARN", MANAGER_ARN, optional=True)
    _check_plain("CREDENTIAL_PROVIDER_ARN_CDP", CREDENTIAL_PROVIDER_ARN_CDP, optional=True)
    _check_plain("CREDENTIAL_PROVIDER_ARN_PRIVY", CREDENTIAL_PROVIDER_ARN_PRIVY, optional=True)
    _check_plain("CONNECTOR_ID_CDP", CONNECTOR_ID_CDP, optional=True)
    _check_plain("CONNECTOR_ID_PRIVY", CONNECTOR_ID_PRIVY, optional=True)
    _check_plain("PAYMENT_INSTRUMENT_ID_CDP_EVM", PAYMENT_INSTRUMENT_ID_CDP_EVM, optional=True)
    _check_plain("PAYMENT_INSTRUMENT_ID_CDP_SOL", PAYMENT_INSTRUMENT_ID_CDP_SOL, optional=True)
    _check_plain("PAYMENT_INSTRUMENT_ID_PRIVY_EVM", PAYMENT_INSTRUMENT_ID_PRIVY_EVM, optional=True)
    _check_plain("PAYMENT_INSTRUMENT_ID_PRIVY_SOL", PAYMENT_INSTRUMENT_ID_PRIVY_SOL, optional=True)
    _check_plain("SESSION_ID_CDP", SESSION_ID_CDP, optional=True)
    _check_plain("SESSION_ID_PRIVY", SESSION_ID_PRIVY, optional=True)

    # Halt before §3 if any required value is missing — the script can't make
    # progress and downstream errors are misleading. Fix .env, save, re-run.
    if not all(required_results):
        missing_count = required_results.count(False)
        sys.exit(
            f"\n❌ {missing_count} required value(s) missing in .env. Fix the entries marked "
            f"❌ MISSING above, save .env, then re-run python pay_for_api.py."
        )
    print("\n✅ Environment check passed.\n")


def _client_token() -> str:
    """AgentCore Payments requires `clientToken` >= 33 chars. UUID v4 is safe."""
    return f"pay-for-api-{uuid.uuid4()}"


def _confirm_section(title: str, body_lines: list[str], action_label: str) -> bool:
    """Show a framed banner + body, then prompt: Enter to run, q + Enter to skip."""
    print("\n" + "=" * 72)
    print(f"  {title}")
    print("=" * 72)
    print()
    for line in body_lines:
        print(line)
    print()
    print(f"  ▶▶ Press Enter to {action_label}, or press q + Enter to skip.")
    choice = input("     [Enter to continue | q to skip] ").strip().lower()
    return choice not in ("q", "quit", "skip", "n", "no")


# ── §3. Provision and sanity-check the seller ───────────────────────────────
def deploy_seller_if_needed() -> None:
    """Run deploy-seller.sh and reload .env if SELLER_API_URL is unset."""
    global SELLER_API_URL
    if SELLER_API_URL:
        print(f"\n↷ Seller already deployed ({SELLER_API_URL}), skipping seller deploy.")
        return

    print("\n=== §3. Deploy the Fun Facts seller via test/integration/deploy-seller.sh ===")
    here = pathlib.Path(__file__).resolve().parent
    proc = subprocess.run(
        ["bash", "test/integration/deploy-seller.sh"],
        cwd=here,
    )
    if proc.returncode != 0:
        sys.exit(f"deploy-seller.sh exited {proc.returncode}")

    # Reload .env to pick up the SELLER_API_URL the script just wrote.
    load_dotenv(override=True)
    SELLER_API_URL = os.environ.get("SELLER_API_URL", "").rstrip("/")
    if not SELLER_API_URL:
        sys.exit("deploy-seller.sh finished but SELLER_API_URL was not written to .env.")
    print(f"\n✅ Seller URL: {SELLER_API_URL}")


def sanity_check_seller() -> None:
    if not SELLER_API_URL:
        sys.exit("SELLER_API_URL is unset — deploy_seller_if_needed() should have populated it.")

    print(f"\n=== §3. Sanity-check the seller — {SELLER_API_URL} ===")
    health = requests.get(f"{SELLER_API_URL}/health", timeout=10)
    health.raise_for_status()
    print(f"Health: {health.json()}")

    # Preview the 402 response — what the agent will see on its first request
    preview = requests.get(f"{SELLER_API_URL}/facts?topic=space", timeout=10)
    print(f"Preview /facts -> HTTP {preview.status_code}")
    if preview.status_code == 402:
        body = preview.json()
        accepts = body.get("accepts") or []
        print(f"x402Version: {body.get('x402Version')}, accepts ({len(accepts)}):")
        for a in accepts:
            print(f"   network={a.get('network')}, payTo={a.get('payTo')}, price={a.get('maxAmountRequired')}")


# ── §4.1 Assume roles + build clients ────────────────────────────────────────
def build_clients() -> dict:
    missing = [
        n
        for n, v in (
            ("CONTROL_PLANE_ROLE_ARN", CONTROL_PLANE_ROLE_ARN),
            ("MANAGEMENT_ROLE_ARN", MANAGEMENT_ROLE_ARN),
            ("RESOURCE_RETRIEVAL_ROLE_ARN", RESOURCE_RETRIEVAL_ROLE_ARN),
        )
        if not v
    ]
    if missing:
        sys.exit(f"Missing IAM roles: {missing}. Run bash test/integration/setup-roles.sh.")

    boto_session = Session(region_name=AWS_REGION)
    print("Assuming ControlPlaneRole...")
    cp_session = assume_role(boto_session, CONTROL_PLANE_ROLE_ARN, "pay-for-api-cp")
    cp_client = cp_session.client("bedrock-agentcore-control")
    cred_client = cp_session.client("bedrock-agentcore-control")

    print("Assuming ManagementRole...")
    mgmt_session = assume_role(boto_session, MANAGEMENT_ROLE_ARN, "pay-for-api-mgmt")
    dp_client_mgmt = mgmt_session.client("bedrock-agentcore")

    print("Assuming ProcessPaymentRole...")
    pp_session = assume_role(boto_session, PROCESS_PAYMENT_ROLE_ARN, "pay-for-api-pp")
    dp_client_pp = pp_session.client("bedrock-agentcore")

    return {
        "cp": cp_client,
        "cred": cred_client,
        "dp_mgmt": dp_client_mgmt,
        "dp_pp": dp_client_pp,
    }


# ── §4.2 Create the Credential Providers ─────────────────────────────────────
# PaymentCredentialProvider is the security handoff. AgentCore Identity stores
# wallet provider secrets in AWS Secrets Manager under KMS encryption and
# surfaces only the secret ARN. The agent runtime never receives the raw secret;
# at signing time it calls GetResourcePaymentToken to obtain a short-lived
# vendor-specific token. After this step runs, the local .env copies of these
# secrets are no longer needed at runtime.
def create_credential_providers(clients: dict) -> tuple[str, str]:
    global CREDENTIAL_PROVIDER_ARN_CDP, CREDENTIAL_PROVIDER_ARN_PRIVY
    cred = clients["cred"]

    # CDP
    if CREDENTIAL_PROVIDER_ARN_CDP:
        print("↷ CREDENTIAL_PROVIDER_ARN_CDP already set, skipping CDP cred provider create")
    else:
        missing_cdp = [
            n
            for n, v in (
                ("COINBASE_API_KEY_ID", COINBASE_API_KEY_ID),
                ("COINBASE_API_KEY_SECRET", COINBASE_API_KEY_SECRET),
                ("COINBASE_WALLET_SECRET", COINBASE_WALLET_SECRET),
            )
            if not v
        ]
        if missing_cdp:
            sys.exit(f"Missing Coinbase secrets in .env: {missing_cdp}")

        cred_name = f"PayForApiCDPCred{uuid.uuid4().hex[:6]}"
        resp = cred.create_payment_credential_provider(
            name=cred_name,
            credentialProviderVendor="CoinbaseCDP",
            providerConfigurationInput={
                "coinbaseCdpConfiguration": {
                    "apiKeyId": COINBASE_API_KEY_ID,
                    "apiKeySecret": COINBASE_API_KEY_SECRET,
                    "walletSecret": COINBASE_WALLET_SECRET,
                }
            },
        )
        CREDENTIAL_PROVIDER_ARN_CDP = resp["credentialProviderArn"]
        write_env_updates(
            {
                "CREDENTIAL_PROVIDER_ARN_CDP": CREDENTIAL_PROVIDER_ARN_CDP,
                "CRED_PROVIDER_NAME_CDP": cred_name,
            }
        )
        print(f"✅ CDP cred provider: {CREDENTIAL_PROVIDER_ARN_CDP}")

    # Privy
    if CREDENTIAL_PROVIDER_ARN_PRIVY:
        print("↷ CREDENTIAL_PROVIDER_ARN_PRIVY already set, skipping Privy cred provider create")
    else:
        missing_privy = [
            n
            for n, v in (
                ("PRIVY_APP_ID", PRIVY_APP_ID),
                ("PRIVY_APP_SECRET", PRIVY_APP_SECRET),
                ("PRIVY_AUTHORIZATION_ID", PRIVY_AUTHORIZATION_ID),
                ("PRIVY_AUTHORIZATION_PRIVATE_KEY", PRIVY_AUTHORIZATION_PRIVATE_KEY),
            )
            if not v
        ]
        if missing_privy:
            print(
                f"↷ Privy values missing from .env ({len(missing_privy)} key(s)), skipping Privy cred provider create"
            )
        else:
            cred_name = f"PayForApiPrivyCred{uuid.uuid4().hex[:6]}"
            resp = cred.create_payment_credential_provider(
                name=cred_name,
                credentialProviderVendor="StripePrivy",
                providerConfigurationInput={
                    "stripePrivyConfiguration": {
                        "appId": PRIVY_APP_ID,
                        "appSecret": PRIVY_APP_SECRET,
                        "authorizationId": PRIVY_AUTHORIZATION_ID,
                        "authorizationPrivateKey": PRIVY_AUTHORIZATION_PRIVATE_KEY,
                    }
                },
            )
            CREDENTIAL_PROVIDER_ARN_PRIVY = resp["credentialProviderArn"]
            write_env_updates(
                {
                    "CREDENTIAL_PROVIDER_ARN_PRIVY": CREDENTIAL_PROVIDER_ARN_PRIVY,
                    "CRED_PROVIDER_NAME_PRIVY": cred_name,
                }
            )
            print(f"✅ Privy cred provider: {CREDENTIAL_PROVIDER_ARN_PRIVY}")

    return CREDENTIAL_PROVIDER_ARN_CDP, CREDENTIAL_PROVIDER_ARN_PRIVY


# ── §4.3 Create the Payment Manager ──────────────────────────────────────────
# One Manager hosts both connectors so a single audit trail covers the whole
# use case. wait_for_status polls until the Manager is READY. The Manager
# stores only the ResourceRetrievalRole; ManagementRole and
# ProcessPaymentRole are session-time roles assumed by the caller.
def create_manager(clients: dict) -> tuple[str, str]:
    global MANAGER_ARN, MANAGER_ID
    cp = clients["cp"]

    if MANAGER_ARN:
        print("↷ MANAGER_ARN already set, skipping manager create")
        return MANAGER_ARN, MANAGER_ID

    # PaymentManager names: letters + digits only, max 48 chars.
    name = f"PayForApi{uuid.uuid4().hex[:8]}"
    resp = cp.create_payment_manager(
        name=name,
        description=f"AgentCore Payments Pay for API use case {name}",
        authorizerType="AWS_IAM",
        roleArn=RESOURCE_RETRIEVAL_ROLE_ARN,
        clientToken=_client_token(),
    )
    MANAGER_ID = resp["paymentManagerId"]
    MANAGER_ARN = resp["paymentManagerArn"]
    print(f"Created Manager {MANAGER_ID}, waiting for READY...")
    wait_for_status(
        cp.get_payment_manager,
        expected_status="READY",
        paymentManagerId=MANAGER_ID,
    )
    write_env_updates({"MANAGER_ARN": MANAGER_ARN, "MANAGER_ID": MANAGER_ID})
    print(f"✅ Manager: {MANAGER_ARN}")
    return MANAGER_ARN, MANAGER_ID


# ── §4.4 Create the Payment Connectors ───────────────────────────────────────
# Two connectors under the same Manager. Each binds to one credential provider.
def create_connectors(clients: dict) -> tuple[str, str]:
    global CONNECTOR_ID_CDP, CONNECTOR_ID_PRIVY
    cp = clients["cp"]

    if CONNECTOR_ID_CDP:
        print("↷ CONNECTOR_ID_CDP already set, skipping CDP connector create")
    else:
        name = f"PayForApiCDPConn{uuid.uuid4().hex[:6]}"
        resp = cp.create_payment_connector(
            paymentManagerId=MANAGER_ID,
            name=name,
            description=f"AgentCore Payments CoinbaseCDP connector {name}",
            type="CoinbaseCDP",
            credentialProviderConfigurations=[{"coinbaseCDP": {"credentialProviderArn": CREDENTIAL_PROVIDER_ARN_CDP}}],
            clientToken=_client_token(),
        )
        CONNECTOR_ID_CDP = resp["paymentConnectorId"]
        wait_for_status(
            cp.get_payment_connector,
            expected_status="READY",
            paymentManagerId=MANAGER_ID,
            paymentConnectorId=CONNECTOR_ID_CDP,
        )
        write_env_updates({"CONNECTOR_ID_CDP": CONNECTOR_ID_CDP})
        print(f"✅ CDP connector: {CONNECTOR_ID_CDP}")

    if CONNECTOR_ID_PRIVY:
        print("↷ CONNECTOR_ID_PRIVY already set, skipping Privy connector create")
    elif not CREDENTIAL_PROVIDER_ARN_PRIVY:
        print("↷ No Privy credential provider — skipping Privy connector create")
    else:
        name = f"PayForApiPrivyConn{uuid.uuid4().hex[:6]}"
        resp = cp.create_payment_connector(
            paymentManagerId=MANAGER_ID,
            name=name,
            description=f"AgentCore Payments StripePrivy connector {name}",
            type="StripePrivy",
            credentialProviderConfigurations=[
                {"stripePrivy": {"credentialProviderArn": CREDENTIAL_PROVIDER_ARN_PRIVY}}
            ],
            clientToken=_client_token(),
        )
        CONNECTOR_ID_PRIVY = resp["paymentConnectorId"]
        wait_for_status(
            cp.get_payment_connector,
            expected_status="READY",
            paymentManagerId=MANAGER_ID,
            paymentConnectorId=CONNECTOR_ID_PRIVY,
        )
        write_env_updates({"CONNECTOR_ID_PRIVY": CONNECTOR_ID_PRIVY})
        print(f"✅ Privy connector: {CONNECTOR_ID_PRIVY}")

    return CONNECTOR_ID_CDP, CONNECTOR_ID_PRIVY


# ── §4.5 Create four Payment Instruments ─────────────────────────────────────
# Two per connector: ETHEREUM (Base Sepolia) + SOLANA (Solana Devnet).
def create_instrument(
    clients: dict,
    *,
    connector_id: str,
    network: str,
    env_key_id: str,
    env_key_wallet: str,
    label: str,
) -> tuple[str, str, str]:
    dp = clients["dp_mgmt"]
    existing = os.environ.get(env_key_id, "")
    if existing:
        print(f"↷ {env_key_id} already set, skipping {label} instrument create")
        return existing, os.environ.get(env_key_wallet, ""), ""

    resp = dp.create_payment_instrument(
        paymentManagerArn=MANAGER_ARN,
        paymentConnectorId=connector_id,
        userId=USER_ID,
        paymentInstrumentType="EMBEDDED_CRYPTO_WALLET",
        paymentInstrumentDetails={
            "embeddedCryptoWallet": {
                "network": network,
                "linkedAccounts": [{"email": {"emailAddress": INSTRUMENT_EMAIL}}],
            }
        },
        clientToken=_client_token(),
    )
    instrument = resp["paymentInstrument"]
    instrument_id = instrument["paymentInstrumentId"]
    crypto = instrument["paymentInstrumentDetails"]["embeddedCryptoWallet"]
    wallet_address = crypto.get("walletAddress", "")
    redirect_url = crypto.get("redirectUrl", "")

    print(f"  Created {label} instrument {instrument_id}, waiting for ACTIVE...")
    wait_for_status(
        dp.get_payment_instrument,
        expected_status="ACTIVE",
        paymentManagerArn=MANAGER_ARN,
        paymentInstrumentId=instrument_id,
        userId=USER_ID,
    )
    # Re-fetch — the walletAddress is populated only after ACTIVE.
    refreshed = dp.get_payment_instrument(
        paymentManagerArn=MANAGER_ARN,
        paymentInstrumentId=instrument_id,
        userId=USER_ID,
    )["paymentInstrument"]
    wallet_address = refreshed["paymentInstrumentDetails"]["embeddedCryptoWallet"].get("walletAddress", "")

    write_env_updates({env_key_id: instrument_id, env_key_wallet: wallet_address})
    print(f"✅ {label} instrument: {instrument_id} (wallet={wallet_address or 'pending'})")
    return instrument_id, wallet_address, redirect_url


def create_all_instruments(clients: dict) -> tuple[dict, str]:
    global PAYMENT_INSTRUMENT_ID_CDP_EVM, WALLET_ADDRESS_CDP_EVM
    global PAYMENT_INSTRUMENT_ID_CDP_SOL, WALLET_ADDRESS_CDP_SOL
    global PAYMENT_INSTRUMENT_ID_PRIVY_EVM, WALLET_ADDRESS_PRIVY_EVM
    global PAYMENT_INSTRUMENT_ID_PRIVY_SOL, WALLET_ADDRESS_PRIVY_SOL

    cdp_evm_id, cdp_evm_wallet, cdp_evm_redirect = create_instrument(
        clients,
        connector_id=CONNECTOR_ID_CDP,
        network="ETHEREUM",
        env_key_id="PAYMENT_INSTRUMENT_ID_CDP_EVM",
        env_key_wallet="WALLET_ADDRESS_CDP_EVM",
        label="CDP EVM",
    )
    PAYMENT_INSTRUMENT_ID_CDP_EVM, WALLET_ADDRESS_CDP_EVM = cdp_evm_id, cdp_evm_wallet

    if cdp_evm_redirect:
        print(f"\n  🔗 Coinbase Wallet Hub: {cdp_evm_redirect}")
        print("     Sign in with INSTRUMENT_EMAIL, grant signing delegation, fund both")
        print("     wallets via faucet.circle.com (Base Sepolia + Solana Devnet).")

    cdp_sol_id, cdp_sol_wallet, _ = create_instrument(
        clients,
        connector_id=CONNECTOR_ID_CDP,
        network="SOLANA",
        env_key_id="PAYMENT_INSTRUMENT_ID_CDP_SOL",
        env_key_wallet="WALLET_ADDRESS_CDP_SOL",
        label="CDP SOLANA",
    )
    PAYMENT_INSTRUMENT_ID_CDP_SOL, WALLET_ADDRESS_CDP_SOL = cdp_sol_id, cdp_sol_wallet

    if CONNECTOR_ID_PRIVY:
        privy_evm_id, privy_evm_wallet, _ = create_instrument(
            clients,
            connector_id=CONNECTOR_ID_PRIVY,
            network="ETHEREUM",
            env_key_id="PAYMENT_INSTRUMENT_ID_PRIVY_EVM",
            env_key_wallet="WALLET_ADDRESS_PRIVY_EVM",
            label="Privy EVM",
        )
        PAYMENT_INSTRUMENT_ID_PRIVY_EVM, WALLET_ADDRESS_PRIVY_EVM = (
            privy_evm_id,
            privy_evm_wallet,
        )

        privy_sol_id, privy_sol_wallet, _ = create_instrument(
            clients,
            connector_id=CONNECTOR_ID_PRIVY,
            network="SOLANA",
            env_key_id="PAYMENT_INSTRUMENT_ID_PRIVY_SOL",
            env_key_wallet="WALLET_ADDRESS_PRIVY_SOL",
            label="Privy SOLANA",
        )
        PAYMENT_INSTRUMENT_ID_PRIVY_SOL, WALLET_ADDRESS_PRIVY_SOL = (
            privy_sol_id,
            privy_sol_wallet,
        )
    else:
        print("↷ No Privy connector — skipping Privy EVM/SOLANA instrument creates")

    instruments = {
        "cdp_evm": (PAYMENT_INSTRUMENT_ID_CDP_EVM, WALLET_ADDRESS_CDP_EVM),
        "cdp_sol": (PAYMENT_INSTRUMENT_ID_CDP_SOL, WALLET_ADDRESS_CDP_SOL),
        "privy_evm": (PAYMENT_INSTRUMENT_ID_PRIVY_EVM, WALLET_ADDRESS_PRIVY_EVM),
        "privy_sol": (PAYMENT_INSTRUMENT_ID_PRIVY_SOL, WALLET_ADDRESS_PRIVY_SOL),
    }
    return instruments, cdp_evm_redirect


# ── §6. Grant signing delegation (CDP browser, Privy frontend) ───────────────
# Both providers require the operator to grant signing delegation through their
# hosted hub before ProcessPayment will succeed. Coinbase opens its hub directly
# in the user's browser. Privy needs a small Next.js frontend that this script
# clones, installs, and launches inline. The user grants delegation in the
# browser, then presses Enter to continue.
PRIVY_FRONTEND_REPO = "https://github.com/privy-io/aws-agentcore-sdk.git"
PRIVY_FRONTEND_DIR = "privy-delegation"


def _wait_for_port(port: int, host: str = "127.0.0.1", timeout: int = 60) -> bool:
    """Block until a TCP port accepts connections, or timeout. True on success."""
    import socket

    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection((host, port), timeout=1):
                return True
        except OSError:
            time.sleep(0.5)
    return False


def grant_cdp_delegation(redirect_url: str) -> None:
    """Open the Coinbase Wallet Hub in the user's browser and wait for confirmation."""
    if os.environ.get("CDP_DELEGATION_GRANTED", "").lower() in ("1", "true", "yes"):
        print("↷ CDP_DELEGATION_GRANTED=1, skipping CDP delegation handoff")
        return
    if not redirect_url:
        print("\n  No CDP redirect URL captured (instrument likely already provisioned).")
        print("  If you have not granted Coinbase Wallet Hub delegation yet, follow the")
        print("  'Coinbase Wallet Hub' steps in README.md → 'Step 5: Grant signing")
        print("  delegation', then re-run with CDP_DELEGATION_GRANTED=1.")
        return

    print("\n" + "=" * 72)
    print("  §6a. Coinbase Wallet Hub delegation")
    print("=" * 72)
    print(f"\n  Opening Coinbase Wallet Hub in your browser:\n    {redirect_url}")
    print("\n  In the hub:")
    print("    1. Sign in with INSTRUMENT_EMAIL.")
    print("    2. Enter the OTP sent to that email.")
    print("    3. Grant signing delegation to the agent. Without this step,")
    print("       ProcessPayment returns 'Delegated signing grant is not active'.")
    print("    4. Set the delegation duration.")
    print("    5. Copy the EVM wallet address and request testnet USDC from")
    print("       https://faucet.circle.com/ on Base Sepolia.")
    print("    6. Toggle to Solana, switch to Solana Devnet, copy the address,")
    print("       and request testnet USDC on Solana Devnet from the same faucet.")

    try:
        webbrowser.open(redirect_url, new=2)
    except Exception:  # noqa: BLE001
        # Headless or no display — user can copy the URL manually.
        pass

    print("\n  ▶▶ Press Enter to continue once Coinbase delegation is granted")
    print("     and both Base Sepolia + Solana Devnet wallets are funded.")
    input("     [Enter to continue] ")


def grant_privy_delegation() -> None:
    """Clone, install, and run the Privy delegation frontend, then wait for confirmation."""
    if os.environ.get("PRIVY_DELEGATION_WIRED_UP", "").lower() in ("1", "true", "yes"):
        print("↷ PRIVY_DELEGATION_WIRED_UP=1, skipping Privy delegation handoff")
        return

    missing_privy = [
        n
        for n, v in (
            ("PRIVY_APP_ID", PRIVY_APP_ID),
            ("PRIVY_APP_SECRET", PRIVY_APP_SECRET),
            ("PRIVY_AUTHORIZATION_ID", PRIVY_AUTHORIZATION_ID),
        )
        if not v
    ]
    if missing_privy:
        print(f"\n  Privy values missing from .env ({len(missing_privy)} key(s)), skipping Privy delegation handoff.")
        return

    print("\n" + "=" * 72)
    print("  §6b. Privy Wallet Hub delegation")
    print("=" * 72)
    print()
    print("  Privy embedded wallets need a separate signing delegation before the")
    print("  agent can call ProcessPayment against them. Without this, ProcessPayment")
    print("  returns 'Delegated signing grant is not active'.")
    print()
    print("  The delegation is granted from a small Next.js frontend maintained")
    print("  jointly by Privy and AWS at https://github.com/privy-io/aws-agentcore-sdk.")
    print("  The script will:")
    print("    1. Clone the frontend into ./privy-delegation/")
    print("    2. Run npm install (one-time, takes ~1 minute)")
    print("    3. Pass PRIVY_* values from .env into the frontend process")
    print("       environment (NETWORK_MODE pinned to testnet so balances show")
    print("       Base Sepolia + Solana Devnet)")
    print("    4. Launch npm run dev on http://localhost:3000 in a background")
    print("       process group (loopback only, no TLS needed for local dev)")

    here = pathlib.Path(__file__).resolve().parent
    frontend_path = here / PRIVY_FRONTEND_DIR

    if not frontend_path.exists():
        print(f"\n  Cloning {PRIVY_FRONTEND_REPO} → {PRIVY_FRONTEND_DIR}")
        proc = subprocess.run(
            ["git", "clone", "--depth", "1", PRIVY_FRONTEND_REPO, str(frontend_path)],
            cwd=str(here),
        )
        if proc.returncode != 0:
            print(f"  ⚠️  git clone exited {proc.returncode}, skipping Privy delegation handoff")
            return
    else:
        print(f"\n  ↷ {PRIVY_FRONTEND_DIR}/ already cloned, reusing")

    if not (frontend_path / "node_modules").exists():
        print("  Running npm install (one-time, takes ~1 min)...")
        proc = subprocess.run(["npm", "install"], cwd=str(frontend_path))
        if proc.returncode != 0:
            print(f"  ⚠️  npm install exited {proc.returncode}, skipping Privy delegation handoff")
            return
    else:
        print("  ↷ node_modules/ already installed, reusing")

    # Pass Privy values to the Next.js dev server through the child process
    # environment instead of writing them to .env.local on disk. Next.js
    # honours process.env at the highest priority (above .env.local), so
    # the frontend reads the same values without any secret hitting the
    # filesystem. The script never persists Privy credentials beyond the
    # parent .env that the operator pasted them into.
    print("\n  Configuring frontend environment (no secrets written to disk).")
    print(f"     App ID:    {PRIVY_APP_ID}")
    print(f"     Signer ID: {PRIVY_AUTHORIZATION_ID}")
    print("     Network:   testnet (Base Sepolia + Solana Devnet)")

    print("\n  Starting Privy frontend (npm run dev) in a new process group...")
    # start_new_session=True puts the child in its own process group so that
    # SIGINT (Ctrl-C) in this terminal does not kill it before we tell it to.
    frontend_env = os.environ.copy()
    frontend_env["NEXT_PUBLIC_PRIVY_APP_ID"] = PRIVY_APP_ID
    frontend_env["PRIVY_APP_SECRET"] = PRIVY_APP_SECRET
    frontend_env["NEXT_PUBLIC_PRIVY_SIGNER_ID"] = PRIVY_AUTHORIZATION_ID
    frontend_env["NEXT_PUBLIC_NETWORK_MODE"] = "testnet"

    proc = subprocess.Popen(
        ["npm", "run", "dev"],
        cwd=str(frontend_path),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        start_new_session=True,
        env=frontend_env,
    )

    # Tail child stdout so the user sees compile errors and the "ready" line.
    def _tail() -> None:
        try:
            assert proc.stdout is not None
            for line in proc.stdout:
                print(f"    [privy] {line.rstrip()}")
        except Exception:  # noqa: BLE001
            pass

    threading.Thread(target=_tail, daemon=True).start()

    try:
        if not _wait_for_port(3000, timeout=120):
            print("  ⚠️  Privy frontend did not open port 3000 within 120s, continuing anyway.")
        else:
            print("  ✅ Privy frontend is listening on http://localhost:3000")
            try:
                webbrowser.open("http://localhost:3000", new=2)
            except Exception:  # noqa: BLE001
                pass

        print("\n  In the Privy hub at http://localhost:3000:")
        print("    1. Log in with INSTRUMENT_EMAIL. Privy sends a one-time passcode")
        print("       (OTP) to that address.")
        print("    2. View your wallets. The hub queries Base Sepolia and Solana")
        print("       Devnet directly and shows USDC balances for both.")
        print("    3. Choose Delegate on each wallet you want the agent to spend")
        print("       from. Without this step, ProcessPayment returns")
        print("       'Delegated signing grant is not active'.")
        print("    4. Choose Receive in the hub to copy each wallet address.")
        print("    5. Request testnet USDC from https://faucet.circle.com/ on")
        print("       Base Sepolia or Solana Devnet using the copied address.")
        print("       (Card funding via Stripe is mainnet-only and is disabled when")
        print("        NEXT_PUBLIC_NETWORK_MODE=testnet.)")
        print()
        print("  Once both wallets show a balance and delegation is granted,")
        print("  return here.")

        print("\n  ▶▶ Press Enter to continue once Privy delegation is granted")
        print("     and both Base Sepolia + Solana Devnet wallets are funded.")
        print("     The script will stop the Privy frontend automatically.")
        input("     [Enter to continue] ")
        # Mark for §7 / §8 loops in this process; not persisted to .env.
        os.environ["PRIVY_DELEGATION_WIRED_UP"] = "1"
    finally:
        print("  Stopping Privy frontend...")
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            proc.wait(timeout=5)
        except (ProcessLookupError, subprocess.TimeoutExpired):
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except ProcessLookupError:
                pass


# ── §5. Create payment sessions ──────────────────────────────────────────────
# Sessions are Manager-scoped, not connector- or instrument-scoped, so a
# single session covers every instrument under the Manager. We create two
# logical sessions (one per provider) so the CDP and Privy spend ledgers
# stay separate. The operator sets maxSpendAmount; AgentCore Payments
# rejects any ProcessPayment that would exceed it.
def create_sessions(clients: dict) -> tuple[str, str]:
    global SESSION_ID_CDP, SESSION_ID_PRIVY
    dp = clients["dp_mgmt"]

    if SESSION_ID_CDP:
        print("↷ SESSION_ID_CDP already set, skipping CDP session create")
    else:
        resp = dp.create_payment_session(
            paymentManagerArn=MANAGER_ARN,
            userId=USER_ID,
            expiryTimeInMinutes=SESSION_EXPIRY_MINUTES,
            limits={"maxSpendAmount": {"value": SESSION_MAX_SPEND, "currency": "USD"}},
            clientToken=_client_token(),
        )
        SESSION_ID_CDP = resp["paymentSession"]["paymentSessionId"]
        write_env_updates({"SESSION_ID_CDP": SESSION_ID_CDP})
        print(f"✅ CDP session: {SESSION_ID_CDP}")

    if SESSION_ID_PRIVY:
        print("↷ SESSION_ID_PRIVY already set, skipping Privy session create")
    elif not (CONNECTOR_ID_PRIVY and PAYMENT_INSTRUMENT_ID_PRIVY_EVM):
        print("↷ No Privy connector or instrument — skipping Privy session create")
    else:
        resp = dp.create_payment_session(
            paymentManagerArn=MANAGER_ARN,
            userId=USER_ID,
            expiryTimeInMinutes=SESSION_EXPIRY_MINUTES,
            limits={"maxSpendAmount": {"value": SESSION_MAX_SPEND, "currency": "USD"}},
            clientToken=_client_token(),
        )
        SESSION_ID_PRIVY = resp["paymentSession"]["paymentSessionId"]
        write_env_updates({"SESSION_ID_PRIVY": SESSION_ID_PRIVY})
        print(f"✅ Privy session: {SESSION_ID_PRIVY}")

    return SESSION_ID_CDP, SESSION_ID_PRIVY


# ── Agent factory (used by §7 and §8) ────────────────────────────────────────
SYSTEM_PROMPT = (
    "You are a research agent powered by Amazon Bedrock AgentCore Payments.\n"
    "\n"
    "Your only tool is `http_request`. Use it to fetch paid facts from the\n"
    "Fun Facts API. Each `GET` returns exactly one fact and costs $0.01 in\n"
    "USDC. The AgentCore Payments plugin pays on your behalf.\n"
    "\n"
    "RULES\n"
    "  1. One `http_request` GET per topic the user asks about.\n"
    "  2. Parse `x402_content.data` to get the `fact` and answer concisely.\n"
    "  3. End every response with the total amount spent in USD.\n"
)


def build_agent(
    *,
    clients: dict,
    instrument_id: str,
    session_id: str,
    network_preferences: list[str],
    label: str,
):
    """Build a Strands Agent with the AgentCorePaymentsPlugin attached.

    `network_preferences` is a CAIP-style priority list (e.g.
    ["base-sepolia", "solana-devnet"]) telling the plugin which entry
    in the seller's 402 accepts[] to match against the instrument.
    """
    from strands import Agent
    from strands.models.bedrock import BedrockModel
    from strands_tools import http_request
    from bedrock_agentcore.payments.integrations.config import (
        AgentCorePaymentsPluginConfig,
    )
    from bedrock_agentcore.payments.integrations.strands.plugin import (
        AgentCorePaymentsPlugin,
    )

    model = BedrockModel(
        model_id="us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        region_name=AWS_REGION,
        temperature=0.7,
    )

    payment_user_id = resolve_payment_user_id(clients, instrument_id)

    plugin_cfg = AgentCorePaymentsPluginConfig(
        payment_manager_arn=MANAGER_ARN,
        user_id=payment_user_id,
        payment_instrument_id=instrument_id,
        payment_session_id=session_id,
        region=AWS_REGION,
        agent_name=f"pay-for-api-agent-{label.lower().replace(' ', '-')}",
        network_preferences_config=network_preferences,
    )
    plugin = AgentCorePaymentsPlugin(config=plugin_cfg)

    return Agent(
        model=model,
        tools=[http_request],
        system_prompt=SYSTEM_PROMPT,
        plugins=[plugin],
    )


def resolve_payment_user_id(clients: dict, instrument_id: str) -> str:
    """Read paymentInstrument.userId — the vendor-level ID payment ops must run under."""
    resp = clients["dp_mgmt"].get_payment_instrument(
        paymentManagerArn=MANAGER_ARN,
        paymentInstrumentId=instrument_id,
        userId=USER_ID,
    )
    return resp["paymentInstrument"]["userId"]


# ── §7. Ask the agents to buy a fact (local run) ─────────────────────────────
def run_local_agents(clients: dict) -> None:
    print("\n=== §7. Local agent runs (4: provider × network) ===")

    runs = [
        {
            "label": "CDP EVM",
            "instrument_id": PAYMENT_INSTRUMENT_ID_CDP_EVM,
            "session_id": SESSION_ID_CDP,
            "network_preferences": ["base-sepolia", "solana-devnet"],
            "topic": "space",
            "skip_unless_delegated": False,
        },
        {
            "label": "CDP SOLANA",
            "instrument_id": PAYMENT_INSTRUMENT_ID_CDP_SOL,
            "session_id": SESSION_ID_CDP,
            "network_preferences": ["solana-devnet", "base-sepolia"],
            "topic": "oceans",
            "skip_unless_delegated": False,
        },
        {
            "label": "Privy EVM",
            "instrument_id": PAYMENT_INSTRUMENT_ID_PRIVY_EVM,
            "session_id": SESSION_ID_PRIVY,
            "network_preferences": ["base-sepolia", "solana-devnet"],
            "topic": "ai",
            "skip_unless_delegated": True,
        },
        {
            "label": "Privy SOLANA",
            "instrument_id": PAYMENT_INSTRUMENT_ID_PRIVY_SOL,
            "session_id": SESSION_ID_PRIVY,
            "network_preferences": ["solana-devnet", "base-sepolia"],
            "topic": "payments",
            "skip_unless_delegated": True,
        },
    ]

    privy_delegation_wired_up = os.environ.get("PRIVY_DELEGATION_WIRED_UP", "0").lower() in ("1", "true", "yes")

    for r in runs:
        if r["skip_unless_delegated"] and not privy_delegation_wired_up:
            print(
                f"\n── {r['label']} skipped — Privy delegation not granted (run §6b or set PRIVY_DELEGATION_WIRED_UP=1) ──"
            )
            continue
        if not r["instrument_id"] or not r["session_id"]:
            print(f"\n── {r['label']} skipped — instrument or session not provisioned ──")
            continue

        print(f"\n── {r['label']} run ({', '.join(r['network_preferences'])}) ──")
        agent = build_agent(
            clients=clients,
            instrument_id=r["instrument_id"],
            session_id=r["session_id"],
            network_preferences=r["network_preferences"],
            label=r["label"],
        )
        prompt = f"Seller URL: {SELLER_API_URL}/facts\n\nBuy me one fact about {r['topic']} from that seller."
        try:
            result = agent(prompt)
            print(f"\n── {r['label']} response ──\n{result}\n")
        except Exception as exc:  # noqa: BLE001
            print(f"❌ {r['label']} failed: {exc}")
        time.sleep(2)  # gentle pacing between Bedrock invokes


# ── §8. Deploy the agent to AgentCore Runtime ────────────────────────────────
# CodeBuild builds the container in AWS — no local Docker required.
def deploy_agent_runtime() -> str:
    """Run deploy-agent.sh and return the AgentRuntimeArn from agent/cdk/outputs.json."""
    print("\n=== §8. Deploy agent runtime via test/integration/deploy-agent.sh ===")
    here = pathlib.Path(__file__).resolve().parent
    proc = subprocess.run(
        ["bash", "test/integration/deploy-agent.sh"],
        cwd=here,
    )
    if proc.returncode != 0:
        sys.exit(f"deploy-agent.sh exited {proc.returncode}")

    outputs_path = here / "agent" / "cdk" / "outputs.json"
    if not outputs_path.exists():
        sys.exit(f"deploy-agent.sh succeeded but {outputs_path} is missing.")
    cdk_outputs = json.loads(outputs_path.read_text())
    stack = cdk_outputs.get("AgentCorePaymentsBuyerAgentStack", {})
    runtime_arn = stack.get("AgentRuntimeArn", "")
    if not runtime_arn:
        sys.exit(f"AgentRuntimeArn not found in {outputs_path}.")
    os.environ["AGENT_RUNTIME_ARN"] = runtime_arn
    print(f"\n✅ Runtime ARN: {runtime_arn}")
    return runtime_arn


def invoke_runtime(clients: dict) -> None:
    runtime_arn = os.environ.get("AGENT_RUNTIME_ARN", "")
    if not runtime_arn:
        sys.exit("AGENT_RUNTIME_ARN is unset — deploy-agent.sh did not finish.")

    print(f"\n=== Invoking runtime {runtime_arn} (4: provider × network) ===")
    runtime_client = boto3.client("bedrock-agentcore", region_name=AWS_REGION)

    runs = [
        {
            "label": "CDP EVM",
            "instrument_id": PAYMENT_INSTRUMENT_ID_CDP_EVM,
            "session_id": SESSION_ID_CDP,
            "network_preferences": ["base-sepolia", "solana-devnet"],
            "topic": "space",
            "skip_unless_delegated": False,
        },
        {
            "label": "CDP SOLANA",
            "instrument_id": PAYMENT_INSTRUMENT_ID_CDP_SOL,
            "session_id": SESSION_ID_CDP,
            "network_preferences": ["solana-devnet", "base-sepolia"],
            "topic": "oceans",
            "skip_unless_delegated": False,
        },
        {
            "label": "Privy EVM",
            "instrument_id": PAYMENT_INSTRUMENT_ID_PRIVY_EVM,
            "session_id": SESSION_ID_PRIVY,
            "network_preferences": ["base-sepolia", "solana-devnet"],
            "topic": "ai",
            "skip_unless_delegated": True,
        },
        {
            "label": "Privy SOLANA",
            "instrument_id": PAYMENT_INSTRUMENT_ID_PRIVY_SOL,
            "session_id": SESSION_ID_PRIVY,
            "network_preferences": ["solana-devnet", "base-sepolia"],
            "topic": "payments",
            "skip_unless_delegated": True,
        },
    ]

    privy_delegation_wired_up = os.environ.get("PRIVY_DELEGATION_WIRED_UP", "0").lower() in ("1", "true", "yes")

    for r in runs:
        if r["skip_unless_delegated"] and not privy_delegation_wired_up:
            print(f"\n── {r['label']} skipped — Privy delegation not granted ──")
            continue
        if not r["instrument_id"] or not r["session_id"]:
            print(f"\n── {r['label']} skipped — instrument or session not provisioned ──")
            continue

        print(f"\n── {r['label']} runtime invoke ──")
        payment_user_id = resolve_payment_user_id(clients, r["instrument_id"])

        payload = json.dumps(
            {
                "prompt": (
                    f"Get me one interesting fact about {r['topic']}. Tell me the total amount spent in USD at the end."
                ),
                "sellerUrl": SELLER_API_URL,
                "managerArn": MANAGER_ARN,
                "instrumentId": r["instrument_id"],
                "sessionId": r["session_id"],
                "paymentUserId": payment_user_id,
                "networkPreferences": r["network_preferences"],
                "region": AWS_REGION,
            }
        ).encode()

        resp = runtime_client.invoke_agent_runtime(
            agentRuntimeArn=runtime_arn,
            qualifier="DEFAULT",
            payload=payload,
        )
        body = resp["response"]
        raw = b"".join(body.iter_chunks()) if hasattr(body, "iter_chunks") else body.read()
        try:
            parsed = json.loads(raw)
            print(parsed.get("response", parsed))
        except (ValueError, TypeError):
            print(raw.decode(errors="replace"))
        time.sleep(2)


# ── §9. Inspect the data plane ───────────────────────────────────────────────
def inspect_data_plane(clients: dict) -> None:
    print("\n=== §9. Data plane inspection ===")
    dp = clients["dp_mgmt"]

    # ── §9.1 GetPaymentSession — the running budget state ───────────────────
    print("\n── §9.1 GetPaymentSession (running budget per session) ──")
    for label, session_id in (("CDP", SESSION_ID_CDP), ("Privy", SESSION_ID_PRIVY)):
        if not session_id:
            print(f"  ↷ {label}: skipped (no session)")
            continue
        try:
            resp = dp.get_payment_session(
                paymentManagerArn=MANAGER_ARN,
                paymentSessionId=session_id,
                userId=USER_ID,
            )
            sess = resp.get("paymentSession", {})
            budget = sess.get("limits", {}).get("maxSpendAmount", {})
            avail = sess.get("availableLimits", {}).get("availableSpendAmount", {})
            print(f"\n  {label} session")
            print(f"    Session ID:  {sess.get('paymentSessionId', session_id)}")
            print(f"    Budget:      {budget.get('value', '?')} {budget.get('currency', '')}")
            print(f"    Remaining:   {avail.get('value', '?')} {avail.get('currency', '')}")
            print(f"    Expires in:  {sess.get('expiryTimeInMinutes', '?')} minutes")
            print(f"    Created at:  {sess.get('createdAt', '?')}")
        except botocore.exceptions.ClientError as exc:
            print(f"  ⚠️  {label} session inspect failed: {exc.response['Error']['Code']}")

    # ── §9.2 GetPaymentInstrumentBalance — on-chain USDC balance ────────────
    # Maps the instrument's CryptoWalletNetwork to a BlockchainChainId:
    #   ETHEREUM -> BASE_SEPOLIA (testnet) / BASE (mainnet)
    #   SOLANA   -> SOLANA_DEVNET / SOLANA
    # tokenBalance.amount is the atomic amount (6 decimals for USDC).
    print("\n── §9.2 GetPaymentInstrumentBalance (on-chain USDC) ──")
    wallets = [
        ("CDP EVM", CONNECTOR_ID_CDP, PAYMENT_INSTRUMENT_ID_CDP_EVM, WALLET_ADDRESS_CDP_EVM, "BASE_SEPOLIA"),
        ("CDP SOLANA", CONNECTOR_ID_CDP, PAYMENT_INSTRUMENT_ID_CDP_SOL, WALLET_ADDRESS_CDP_SOL, "SOLANA_DEVNET"),
        ("Privy EVM", CONNECTOR_ID_PRIVY, PAYMENT_INSTRUMENT_ID_PRIVY_EVM, WALLET_ADDRESS_PRIVY_EVM, "BASE_SEPOLIA"),
        (
            "Privy SOLANA",
            CONNECTOR_ID_PRIVY,
            PAYMENT_INSTRUMENT_ID_PRIVY_SOL,
            WALLET_ADDRESS_PRIVY_SOL,
            "SOLANA_DEVNET",
        ),
    ]
    for label, connector_id, instrument_id, wallet_address, chain in wallets:
        if not instrument_id or not connector_id:
            print(f"  ↷ {label}: skipped (no instrument)")
            continue
        try:
            payment_user_id = resolve_payment_user_id(clients, instrument_id)
            resp = dp.get_payment_instrument_balance(
                paymentManagerArn=MANAGER_ARN,
                paymentConnectorId=connector_id,
                paymentInstrumentId=instrument_id,
                userId=payment_user_id,
                chain=chain,
                token="USDC",
            )
            bal = resp.get("tokenBalance", {})
            amount = int(bal.get("amount", "0")) / (10 ** int(bal.get("decimals", 6)))
            print(f"\n  {label} ({chain})")
            print(f"    Wallet:  {wallet_address or '(no address)'}")
            print(f"    Balance: {amount:.6f} {bal.get('token', 'USDC')}")
        except botocore.exceptions.ClientError as exc:
            print(f"  ⚠️  {label} balance lookup failed: {exc.response['Error']['Code']}")

    # ── §9.3 ListPaymentInstruments — enumerate instruments ─────────────────
    # The summary is thin (no walletAddress/network), so hydrate via
    # GetPaymentInstrument for each entry.
    print("\n── §9.3 ListPaymentInstruments (audit view) ──")
    for label, connector_id, anchor_instrument_id in (
        ("CDP", CONNECTOR_ID_CDP, PAYMENT_INSTRUMENT_ID_CDP_EVM),
        ("Privy", CONNECTOR_ID_PRIVY, PAYMENT_INSTRUMENT_ID_PRIVY_EVM),
    ):
        if not anchor_instrument_id or not connector_id:
            print(f"  ↷ {label}: skipped (no instrument)")
            continue
        try:
            payment_user_id = resolve_payment_user_id(clients, anchor_instrument_id)
            resp = dp.list_payment_instruments(
                paymentManagerArn=MANAGER_ARN,
                paymentConnectorId=connector_id,
                userId=payment_user_id,
                maxResults=20,
            )
            summaries = resp.get("paymentInstruments", [])
            print(f"\n  {label} instruments ({len(summaries)})")
            for i, summary in enumerate(summaries, start=1):
                full = dp.get_payment_instrument(
                    paymentManagerArn=MANAGER_ARN,
                    paymentInstrumentId=summary["paymentInstrumentId"],
                    userId=payment_user_id,
                )["paymentInstrument"]
                crypto = full.get("paymentInstrumentDetails", {}).get("embeddedCryptoWallet", {})
                address = crypto.get("walletAddress", "(no address)")
                network = crypto.get("network", "?")
                status = full.get("status", "?")
                print(f"    [{i}] {full['paymentInstrumentId']}  ({network}, {status})")
                print(f"        Wallet: {address}")
        except botocore.exceptions.ClientError as exc:
            print(f"  ⚠️  {label} instrument list failed: {exc.response['Error']['Code']}")

    # ── §9.4 ListPaymentSessions — enumerate sessions ───────────────────────
    print("\n── §9.4 ListPaymentSessions (audit view) ──")
    for label, anchor_instrument_id in (
        ("CDP", PAYMENT_INSTRUMENT_ID_CDP_EVM),
        ("Privy", PAYMENT_INSTRUMENT_ID_PRIVY_EVM),
    ):
        if not anchor_instrument_id:
            print(f"  ↷ {label}: skipped (no instrument)")
            continue
        try:
            payment_user_id = resolve_payment_user_id(clients, anchor_instrument_id)
            resp = dp.list_payment_sessions(
                paymentManagerArn=MANAGER_ARN,
                userId=payment_user_id,
                maxResults=20,
            )
            summaries = resp.get("paymentSessions", [])
            print(f"\n  {label} sessions ({len(summaries)})")
            for i, summary in enumerate(summaries, start=1):
                full = dp.get_payment_session(
                    paymentManagerArn=MANAGER_ARN,
                    paymentSessionId=summary["paymentSessionId"],
                    userId=payment_user_id,
                )["paymentSession"]
                budget = full.get("limits", {}).get("maxSpendAmount", {})
                avail = full.get("availableLimits", {}).get("availableSpendAmount", {})
                print(f"    [{i}] {full['paymentSessionId']}")
                print(f"        Budget:    {budget.get('value', '?')} {budget.get('currency', '')}")
                print(f"        Remaining: {avail.get('value', '?')} {avail.get('currency', '')}")
                print(f"        Expires:   {full.get('expiryTimeInMinutes', '?')} min")
                print(f"        Created:   {full.get('createdAt', '?')}")
        except botocore.exceptions.ClientError as exc:
            print(f"  ⚠️  {label} session list failed: {exc.response['Error']['Code']}")


# ── §10. Cleanup ─────────────────────────────────────────────────────────────
def _safe_delete(fn, label: str, **kwargs) -> None:
    try:
        fn(**kwargs)
        print(f"  ✅ Deleted: {label}")
    except botocore.exceptions.ClientError as exc:
        code = exc.response["Error"]["Code"]
        msg = exc.response["Error"].get("Message", "")
        if code == "ResourceNotFoundException" or (code == "AccessDeniedException" and "not found" in msg.lower()):
            print(f"  ⚠️  Not found: {label}")
        else:
            print(f"  ❌ {label}: {code} — {msg}")


def cleanup(clients: dict) -> None:
    print("\n=== §10. Cleanup ===")
    cp, dp_mgmt, cred = clients["cp"], clients["dp_mgmt"], clients["cred"]

    for label, session_id in (("CDP", SESSION_ID_CDP), ("Privy", SESSION_ID_PRIVY)):
        if session_id:
            _safe_delete(
                dp_mgmt.delete_payment_session,
                f"{label} session ({session_id})",
                paymentManagerArn=MANAGER_ARN,
                paymentSessionId=session_id,
                userId=USER_ID,
            )

    instruments = [
        ("CDP EVM", CONNECTOR_ID_CDP, PAYMENT_INSTRUMENT_ID_CDP_EVM),
        ("CDP SOLANA", CONNECTOR_ID_CDP, PAYMENT_INSTRUMENT_ID_CDP_SOL),
        ("Privy EVM", CONNECTOR_ID_PRIVY, PAYMENT_INSTRUMENT_ID_PRIVY_EVM),
        ("Privy SOLANA", CONNECTOR_ID_PRIVY, PAYMENT_INSTRUMENT_ID_PRIVY_SOL),
    ]
    for label, connector_id, instrument_id in instruments:
        if not (instrument_id and connector_id):
            continue
        try:
            payment_user_id = resolve_payment_user_id(clients, instrument_id)
        except botocore.exceptions.ClientError:
            print(f"  ⚠️  {label} ({instrument_id}) — manager already gone, skipping")
            continue
        _safe_delete(
            dp_mgmt.delete_payment_instrument,
            f"Instrument {label} ({instrument_id})",
            paymentManagerArn=MANAGER_ARN,
            paymentConnectorId=connector_id,
            paymentInstrumentId=instrument_id,
            userId=payment_user_id,
        )

    for label, connector_id in (
        ("CDP", CONNECTOR_ID_CDP),
        ("Privy", CONNECTOR_ID_PRIVY),
    ):
        if connector_id:
            _safe_delete(
                cp.delete_payment_connector,
                f"{label} connector ({connector_id})",
                paymentManagerId=MANAGER_ID,
                paymentConnectorId=connector_id,
                clientToken=_client_token(),
            )

    if MANAGER_ID:
        _safe_delete(
            cp.delete_payment_manager,
            f"Manager {MANAGER_ID}",
            paymentManagerId=MANAGER_ID,
            clientToken=_client_token(),
        )

    for label, name_var in (
        ("CDP", "CRED_PROVIDER_NAME_CDP"),
        ("Privy", "CRED_PROVIDER_NAME_PRIVY"),
    ):
        name = os.environ.get(name_var, "")
        if name:
            _safe_delete(
                cred.delete_payment_credential_provider,
                f"{label} credential provider ({name})",
                name=name,
            )

    write_env_updates(
        {
            "MANAGER_ID": "",
            "MANAGER_ARN": "",
            "CRED_PROVIDER_NAME_CDP": "",
            "CREDENTIAL_PROVIDER_ARN_CDP": "",
            "CRED_PROVIDER_NAME_PRIVY": "",
            "CREDENTIAL_PROVIDER_ARN_PRIVY": "",
            "CONNECTOR_ID_CDP": "",
            "CONNECTOR_ID_PRIVY": "",
            "PAYMENT_INSTRUMENT_ID_CDP_EVM": "",
            "WALLET_ADDRESS_CDP_EVM": "",
            "PAYMENT_INSTRUMENT_ID_CDP_SOL": "",
            "WALLET_ADDRESS_CDP_SOL": "",
            "PAYMENT_INSTRUMENT_ID_PRIVY_EVM": "",
            "WALLET_ADDRESS_PRIVY_EVM": "",
            "PAYMENT_INSTRUMENT_ID_PRIVY_SOL": "",
            "WALLET_ADDRESS_PRIVY_SOL": "",
            "SESSION_ID_CDP": "",
            "SESSION_ID_PRIVY": "",
            "SELLER_API_URL": "",
        }
    )
    print("\n✅ AgentCore Payments resources cleaned up. .env cleared of provisioned IDs.")

    # ── Tear down the CDK stacks ────────────────────────────────────────────
    here = pathlib.Path(__file__).resolve().parent
    _run_destroy_script(here, "destroy-seller.sh", "Fun Facts seller stack")
    _run_destroy_script(here, "destroy-agent.sh", "agent runtime stack")

    # ── Remove local build artifacts ────────────────────────────────────────
    _remove_local_artifacts(here)

    print("\n✅ Cleanup complete.")


def _run_destroy_script(here: pathlib.Path, script_name: str, label: str) -> None:
    """Run a destroy-*.sh script under test/integration/ if it exists."""
    script = here / "test" / "integration" / script_name
    if not script.exists():
        print(f"\n  ↷ {label}: {script_name} not found, skipping")
        return
    print(f"\n=== Tearing down {label} via test/integration/{script_name} ===")
    proc = subprocess.run(["bash", str(script)], cwd=str(here))
    if proc.returncode != 0:
        # Don't sys.exit — keep teardown going. The user can re-run if needed.
        print(f"  ⚠️  {script_name} exited {proc.returncode}; continuing with remaining cleanup")


def _remove_local_artifacts(here: pathlib.Path) -> None:
    """Remove local CDK build artifacts and runtime caches.

    Matches the notebook's §72 cleanup. None of these hold cloud state,
    so clearing them is safe and keeps the repo clean for the next run.
    """
    import shutil

    print("\n=== Removing local build artifacts ===")
    targets = [
        # Seller CDK
        here / "seller" / "cdk" / ".venv",
        here / "seller" / "cdk" / "cdk.out",
        here / "seller" / "cdk" / "__pycache__",
        here / "seller" / "cdk" / "outputs.json",
        # Seller Lambda npm modules (~16k files of x402 facilitator deps)
        here / "seller" / "lambda" / "node_modules",
        here / "seller" / "lambda" / "package-lock.json",
        # Agent CDK
        here / "agent" / "cdk" / ".venv",
        here / "agent" / "cdk" / "cdk.out",
        here / "agent" / "cdk" / "__pycache__",
        here / "agent" / "cdk" / "outputs.json",
        # Use-case-root caches
        here / "__pycache__",
        here / "test" / "integration" / "__pycache__",
        # Privy Wallet Hub frontend (cloned at runtime by §6b)
        here / "privy-delegation",
        # Use-case-root venv and env file. Removed last so a re-run starts
        # from a clean slate; gitignored so they would never be committed,
        # but we delete them anyway to keep the working tree tidy.
        here / ".venv",
        here / ".env",
    ]

    for path in targets:
        if not path.exists():
            print(f"  ↷ skip (absent): {path.relative_to(here)}")
            continue
        try:
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
            print(f"  🗑️  removed: {path.relative_to(here)}")
        except OSError as exc:
            print(f"  ⚠️  could not remove {path.relative_to(here)}: {exc}")


# ── main ─────────────────────────────────────────────────────────────────────
def main() -> None:
    deploy_seller_if_needed()
    sanity_check_seller()

    print("\n=== §4. Set up AgentCore Payments ===")
    clients = build_clients()
    create_credential_providers(clients)
    create_manager(clients)
    create_connectors(clients)
    _, cdp_redirect_url = create_all_instruments(clients)

    create_sessions(clients)

    grant_cdp_delegation(cdp_redirect_url)
    grant_privy_delegation()

    run_local_agents(clients)

    if _confirm_section(
        "§8. Deploy the agent to AgentCore Runtime",
        [
            "  This step packages the agent into a container and deploys it to",
            "  AgentCore Runtime via AWS CodeBuild (no local Docker required).",
            "  The deploy takes about 4-6 minutes on the first run.",
            "",
            "  Resources created:",
            "    - Amazon ECR repository for the container image",
            "    - AWS CodeBuild project that builds the image",
            "    - AgentCore Runtime + AgentCore Memory resource",
            "    - Supporting CloudWatch log groups and X-Ray traces",
            "",
            "  After deploy, the script invokes the runtime once per",
            "  (provider, network) — same four-run matrix as §7.",
        ],
        "deploy and invoke the runtime",
    ):
        deploy_agent_runtime()
        invoke_runtime(clients)
    else:
        print("\n  ↷ §8 skipped. Continuing to §9 with local agent runs only.")

    inspect_data_plane(clients)

    if _confirm_section(
        "§10. Cleanup",
        [
            "  AgentCore Payments resources, the AgentCore Runtime, and the",
            "  Fun Facts seller stack incur charges while running. Cleanup",
            "  removes:",
            "    - The two payment sessions (DeletePaymentSession)",
            "    - The four payment instruments (DeletePaymentInstrument)",
            "    - The two connectors (DeletePaymentConnector)",
            "    - The Manager (DeletePaymentManager)",
            "    - Both credential providers (DeletePaymentCredentialProvider)",
            "",
            "  CDK stacks are torn down automatically:",
            "    - bash test/integration/destroy-seller.sh",
            "    - bash test/integration/destroy-agent.sh",
            "",
            "  Local build artifacts are removed: seller/cdk/.venv,",
            "  seller/cdk/cdk.out, seller/lambda/node_modules,",
            "  agent/cdk/.venv, agent/cdk/cdk.out, privy-delegation/,",
            "  __pycache__, outputs.json, .venv, .env.",
        ],
        "tear down everything",
    ):
        cleanup(clients)
    else:
        print("\n  ↷ Cleanup skipped. Resources are retained.")


if __name__ == "__main__":
    # Standalone local-cleanup mode — does not touch AWS, just removes the
    # local files cleanup() would otherwise remove. Useful for testing the
    # local-artifact removal in isolation.
    if "--cleanup-local" in sys.argv:
        _remove_local_artifacts(pathlib.Path(__file__).resolve().parent)
        sys.exit(0)
    _run_env_check()
    main()
